import { createClient, type SdkworkDeployBackendClient } from "@sdkwork/deployments-backend-sdk";
import type { AuthTokenManager } from "@sdkwork/sdk-common";
import { normalizeDeploymentsPage, type DeploymentsAction, type DeploymentsActionContext, type DeploymentsDataSource, type DeploymentsRegistry } from "@sdkwork/deployments-pc-commons";
import { createContext, useContext, type ReactNode } from "react";
const Context = createContext<SdkworkDeployBackendClient | null>(null);
export function createDeploymentsAdminClient(baseUrl: string, tokenManager: AuthTokenManager) { return createClient({ baseUrl, authMode: "dual-token", platform: "pc", tokenManager }); }
export function DeploymentsAdminProvider({ children, client }: { children: ReactNode; client: SdkworkDeployBackendClient }) { return <Context.Provider value={client}>{children}</Context.Provider>; }
export function useDeploymentsAdminClient() { const value = useContext(Context); if (!value) throw new Error("DeploymentsAdminProvider is required"); return value; }
export function createDeploymentsAdminRegistry(client: SdkworkDeployBackendClient): DeploymentsRegistry { return { nginx: source((query) => client.nginx.configs.list({ page: query.page, pageSize: query.pageSize }), [action("create", "Create config", { name: "", content: "", description: "" }, (context) => client.nginx.configs.create(context.body as unknown as Parameters<typeof client.nginx.configs.create>[0])), action("validate", "Validate", {}, (context) => client.nginx.configs.validate(selected(context, "id")), { selection: true }), action("deploy", "Deploy", {}, (context) => client.nginx.configs.deploy(selected(context, "id")), { dangerous: true, selection: true }), action("reload", "Reload", {}, () => client.nginx.runtime.reload(), { dangerous: true })]), servers: source((query) => client.server.list({ page: query.page, pageSize: query.pageSize }), [action("create", "Register server", { name: "", host: "", port: 443 }, (context) => client.server.create(context.body as unknown as Parameters<typeof client.server.create>[0]))]), audit: source((query) => client.audit.auditLogs.list({ page: query.page, pageSize: query.pageSize }), []) }; }
function source(load: (query: Parameters<DeploymentsDataSource["load"]>[0]) => Promise<unknown>, actions: readonly DeploymentsAction[]): DeploymentsDataSource { return { actions, async load(query) { return normalizeDeploymentsPage(await load(query)); } }; }
function action(id: string, label: string, bodyTemplate: Record<string, unknown>, execute: DeploymentsAction["execute"], options: { dangerous?: boolean; selection?: boolean } = {}): DeploymentsAction { return { id, label, bodyTemplate, execute, dangerous: options.dangerous, requiresSelection: options.selection }; }
function selected(context: DeploymentsActionContext, field: string): string { const value = context.selectedItem?.[field] ?? context.selectedItem?.configId; if (typeof value !== "string" && typeof value !== "number") throw new Error(`${field} is unavailable`); return String(value); }

