import { createClient as createDeployClient, type SdkworkDeployAppClient } from "@sdkwork/deploy-app-sdk";
import { createDriveAppClient, type SdkworkDriveAppClient } from "@sdkwork/drive-app-sdk";
import type { AuthTokenManager } from "@sdkwork/sdk-common";
import { normalizeDeploymentsPage, type DeploymentsAction, type DeploymentsActionContext, type DeploymentsDataSource, type DeploymentsRegistry } from "@sdkwork/deployments-pc-commons";
import { createContext, useContext, type ReactNode } from "react";
export interface DeploymentsConsoleClients { deploy: SdkworkDeployAppClient; drive: SdkworkDriveAppClient; }
const Context = createContext<DeploymentsConsoleClients | null>(null);
export function createDeploymentsConsoleClients(config: { deployBaseUrl: string; driveBaseUrl: string; tokenManager: AuthTokenManager }): DeploymentsConsoleClients { const common = { authMode: "dual-token" as const, platform: "pc", tokenManager: config.tokenManager }; return { deploy: createDeployClient({ ...common, baseUrl: config.deployBaseUrl }), drive: createDriveAppClient({ ...common, baseUrl: config.driveBaseUrl }) }; }
export function DeploymentsConsoleProvider({ children, clients }: { children: ReactNode; clients: DeploymentsConsoleClients }) { return <Context.Provider value={clients}>{children}</Context.Provider>; }
export function useDeploymentsConsoleClients(): DeploymentsConsoleClients { const value = useContext(Context); if (!value) throw new Error("DeploymentsConsoleProvider is required"); return value; }

export function createDeploymentsConsoleRegistry(clients: DeploymentsConsoleClients): DeploymentsRegistry { const client = clients.deploy; return {
  sites: source((query) => client.site.list({ page: query.page, pageSize: query.pageSize, keyword: query.search }), [action("create", "Create application", { name: "", slug: "", description: "", siteType: 1 }, (context) => client.site.create(context.body as unknown as Parameters<typeof client.site.create>[0])), action("update", "Update", { name: "", description: "" }, (context) => client.site.update(selected(context, "id"), context.body as unknown as Parameters<typeof client.site.update>[1]), { selection: true }), action("activate", "Activate", {}, (context) => client.site.activate(selected(context, "id")), { selection: true }), action("pause", "Disable", {}, (context) => client.site.pause(selected(context, "id")), { dangerous: true, selection: true }), action("delete", "Delete", {}, (context) => client.site.delete(selected(context, "id")), { dangerous: true, selection: true })]),
  configuration: scoped((query) => client.envVariable.sites.envVariables.list(required(query.scopeId), { environment: query.search }), [action("variable", "Add variable", { key: "", value: "", environment: "production", isSecret: false }, (context) => client.envVariable.sites.envVariables.create(required(context.scopeId), context.body as unknown as Parameters<typeof client.envVariable.sites.envVariables.create>[1]), { scope: true }), action("check", "Add health check", { name: "", url: "", checkInterval: 30 }, (context) => client.monitor.sites.healthChecks.create(required(context.scopeId), context.body as unknown as Parameters<typeof client.monitor.sites.healthChecks.create>[1]), { scope: true })]),
  domains: scoped((query) => client.domain.sites.domains.list(required(query.scopeId), { page: query.page, pageSize: query.pageSize }), [action("bind", "Bind domain", { hostname: "", isPrimary: false, sslEnabled: true }, (context) => client.domain.sites.domains.create(required(context.scopeId), context.body as unknown as Parameters<typeof client.domain.sites.domains.create>[1]), { scope: true }), action("verify", "Verify", {}, (context) => client.domain.sites.domains.verify(required(context.scopeId), selected(context, "id")), { scope: true, selection: true }), action("delete", "Unbind", {}, (context) => client.domain.sites.domains.delete(required(context.scopeId), selected(context, "id")), { dangerous: true, scope: true, selection: true })]),
  certificates: source((query) => client.certificate.list({ page: query.page, pageSize: query.pageSize }), [action("create", "Request managed certificate", { certName: "", domainId: "", provider: "letsencrypt", autoRenew: true }, (context) => client.certificate.create(context.body as unknown as Parameters<typeof client.certificate.create>[0])), action("renew", "Renew", {}, (context) => client.certificate.renew(selected(context, "id")), { selection: true }), action("delete", "Delete", {}, (context) => client.certificate.delete(selected(context, "id")), { dangerous: true, selection: true })]),
  artifacts: source((query) => client.artifact.list({ page: query.page, pageSize: query.pageSize }), [action("upload", "Upload application", { packageType: 1, checksumSha256: "" }, async (context) => { const file = context.file; const siteId = required(context.scopeId); if (!file) throw new Error("Package file is required"); const idempotencyKey = crypto.randomUUID(); const uploaded = await clients.drive.uploader.uploadArchive({ file, appResourceType: "deploy.artifact", appResourceId: siteId, scene: "deployment-package", source: "sdkwork-deployments-pc", originalFileName: file.name, contentType: file.type || "application/octet-stream" }); return client.artifact.create({ siteId, packageType: Number(context.body.packageType ?? 1), fileName: file.name, contentType: file.type || "application/octet-stream", contentLength: String(file.size), checksumSha256: stringValue(context.body.checksumSha256) || uploaded.uploadItem.checksumSha256Hex, driveUploadSessionId: uploaded.uploadSession.id, driveUploadItemId: uploaded.uploadItem.id, driveSpaceId: uploaded.uploadItem.spaceId, driveNodeId: uploaded.uploadItem.nodeId, idempotencyKey }); }, { file: true, scope: true }), action("delete", "Retain and remove", {}, (context) => client.artifact.delete(selected(context, "id")), { dangerous: true, selection: true })]),
  releases: scoped((query) => client.release.sites.releases.list(required(query.scopeId), { page: query.page, pageSize: query.pageSize }), [action("create", "Create release", { artifactId: "", versionTag: "", idempotencyKey: "" }, (context) => client.release.sites.releases.create(required(context.scopeId), withIdempotency(context.body) as unknown as Parameters<typeof client.release.sites.releases.create>[1]), { scope: true })]),
  deployments: scoped((query) => client.deployment.sites.deployments.list(required(query.scopeId), { page: query.page, pageSize: query.pageSize }), [action("deploy", "Start deployment", { deployType: 1, releaseId: "", environment: "production", idempotencyKey: "" }, (context) => client.deployment.sites.deployments.create(required(context.scopeId), withIdempotency(context.body) as unknown as Parameters<typeof client.deployment.sites.deployments.create>[1]), { scope: true }), action("rollback", "Rollback", {}, (context) => client.deployment.sites.deployments.rollback(required(context.scopeId), selected(context, "id")), { dangerous: true, scope: true, selection: true })]),
  monitoring: scoped((query) => client.monitor.sites.healthChecks.list(required(query.scopeId)), [action("create", "Add health check", { name: "", url: "", checkInterval: 30 }, (context) => client.monitor.sites.healthChecks.create(required(context.scopeId), context.body as unknown as Parameters<typeof client.monitor.sites.healthChecks.create>[1]), { scope: true })]),
}; }
function source(load: (query: Parameters<DeploymentsDataSource["load"]>[0]) => Promise<unknown>, actions: readonly DeploymentsAction[]): DeploymentsDataSource { return { actions, async load(query) { return normalizeDeploymentsPage(await load(query)); } }; }
function scoped(load: Parameters<typeof source>[0], actions: readonly DeploymentsAction[]): DeploymentsDataSource { return { ...source(load, actions), requiresScope: true }; }
function action(id: string, label: string, bodyTemplate: Record<string, unknown>, execute: DeploymentsAction["execute"], options: { dangerous?: boolean; file?: boolean; scope?: boolean; selection?: boolean } = {}): DeploymentsAction { return { id, label, bodyTemplate, execute, dangerous: options.dangerous, requiresFile: options.file, requiresScope: options.scope, requiresSelection: options.selection }; }
function required(value: string | undefined): string { if (!value?.trim()) throw new Error("Site ID is required"); return value.trim(); }
function selected(context: DeploymentsActionContext, field: string): string { const value = context.selectedItem?.[field]; if (typeof value !== "string" && typeof value !== "number") throw new Error(`${field} is unavailable`); return String(value); }
function stringValue(value: unknown): string | undefined { return typeof value === "string" && value.trim() ? value.trim() : undefined; }
function withIdempotency(body: Record<string, unknown>): Record<string, unknown> { return { ...body, idempotencyKey: stringValue(body.idempotencyKey) ?? crypto.randomUUID() }; }
