[package]
name = "sdkwork-deploy-drive-port"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
sdkwork-deploy-contract.workspace = true
sdkwork-utils-rust.workspace = true
sdkwork-database-id.workspace = true
sdkwork_drive_app_sdk_generated_rust = { package = "sdkwork-drive-app-sdk-generated-rust", path = "../../../sdkwork-drive/sdks/sdkwork-drive-app-sdk/sdkwork-drive-app-sdk-rust/generated/server-openapi" }
