-- SDKWork deploy consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_deploy_legacy_baseline.sql
-- Consolidated legacy baseline imported by bootstrap-database-module.mjs
-- Review and replace with contract-first migrations.

-- source: migrations/001_create_deploy_site.sql
-- Migration: 001_create_deploy_site
-- Description: 创建站点管理主表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_site (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    organization_id BIGINT       NOT NULL DEFAULT 0,
    data_scope      INTEGER      NOT NULL DEFAULT 1,
    user_id         BIGINT,
    name            VARCHAR(100) NOT NULL,
    slug            VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    site_type       INTEGER      NOT NULL DEFAULT 1,
    status          INTEGER      NOT NULL DEFAULT 0,
    runtime_config  JSONB        NOT NULL DEFAULT '{}',
    metadata        JSONB        NOT NULL DEFAULT '{}',
    default_variant_id BIGINT,
    current_revision_id BIGINT,
    desired_revision_id BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    deleted_at      TIMESTAMPTZ,
    deleted_by      BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_site_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_slug UNIQUE (tenant_id, slug),
    CONSTRAINT chk_deploy_site_type CHECK (site_type BETWEEN 1 AND 6),
    CONSTRAINT chk_deploy_site_status CHECK (status BETWEEN 0 AND 3)
);

COMMENT ON TABLE deploy_site IS '站点主表';
COMMENT ON COLUMN deploy_site.id IS '雪花ID主键';
COMMENT ON COLUMN deploy_site.uuid IS '外部稳定标识';
COMMENT ON COLUMN deploy_site.tenant_id IS '租户ID';
COMMENT ON COLUMN deploy_site.organization_id IS '组织ID，0表示租户级';
COMMENT ON COLUMN deploy_site.data_scope IS '数据可见范围：1=私有，2=组织，3=租户';
COMMENT ON COLUMN deploy_site.user_id IS '创建者用户ID';
COMMENT ON COLUMN deploy_site.name IS '站点名称';
COMMENT ON COLUMN deploy_site.slug IS 'URL友好标识，租户内唯一';
COMMENT ON COLUMN deploy_site.site_type IS '站点类型：1=静态，2=SPA，3=Node，4=PHP，5=Python，6=自定义';
COMMENT ON COLUMN deploy_site.status IS '状态：0=草稿，1=活跃，2=暂停，3=归档';
COMMENT ON COLUMN deploy_site.runtime_config IS '运行时配置JSON';
COMMENT ON COLUMN deploy_site.version IS '乐观锁版本号';

CREATE INDEX idx_deploy_site_tenant_status_updated
    ON deploy_site (tenant_id, organization_id, status, updated_at DESC);

CREATE INDEX idx_deploy_site_user_updated
    ON deploy_site (tenant_id, user_id, updated_at DESC);

CREATE INDEX idx_deploy_site_slug
    ON deploy_site (tenant_id, slug);

CREATE TABLE deploy_dns_zone (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(36)  NOT NULL,
    tenant_id       BIGINT       NOT NULL,
    organization_id BIGINT       NOT NULL DEFAULT 0,
    apex_hostname   VARCHAR(253) NOT NULL,
    display_name    VARCHAR(200),
    dns_provider    VARCHAR(64),
    provider_zone_ref VARCHAR(512),
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_by      BIGINT,
    updated_by      BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version         BIGINT       NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMPTZ,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_dns_zone_uuid UNIQUE (uuid),
    CONSTRAINT chk_deploy_dns_zone_status CHECK (status IN ('ACTIVE', 'PAUSED'))
);

CREATE UNIQUE INDEX uk_deploy_dns_zone_active_apex
    ON deploy_dns_zone (apex_hostname)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_deploy_dns_zone_tenant_updated
    ON deploy_dns_zone (tenant_id, updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;

-- source: migrations/002_create_deploy_domain.sql
-- Migration: 002_create_deploy_domain
-- Description: 创建域名绑定表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_domain (
    id                  BIGINT       NOT NULL,
    uuid                VARCHAR(36)  NOT NULL,
    tenant_id           BIGINT       NOT NULL,
    organization_id     BIGINT       NOT NULL DEFAULT 0,
    zone_id             BIGINT       NOT NULL,
    hostname_ascii      VARCHAR(253) NOT NULL,
    hostname_type       VARCHAR(16)  NOT NULL DEFAULT 'EXACT',
    verification_status VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    verified_at         TIMESTAMPTZ,
    status              VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    metadata            JSONB        NOT NULL DEFAULT '{}',
    created_by          BIGINT,
    updated_by          BIGINT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version             BIGINT       NOT NULL DEFAULT 1,
    deleted_at          TIMESTAMPTZ,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_domain_uuid UNIQUE (uuid),
    CONSTRAINT fk_deploy_domain_zone FOREIGN KEY (zone_id) REFERENCES deploy_dns_zone(id),
    CONSTRAINT chk_deploy_domain_hostname_type CHECK (hostname_type IN ('EXACT', 'WILDCARD')),
    CONSTRAINT chk_deploy_domain_verification_status CHECK (verification_status IN ('PENDING', 'VERIFIED', 'FAILED', 'EXPIRED')),
    CONSTRAINT chk_deploy_domain_status CHECK (status IN ('ACTIVE', 'PAUSED')),
    CONSTRAINT chk_deploy_domain_verified_at CHECK (
        (verification_status = 'VERIFIED' AND verified_at IS NOT NULL)
        OR (verification_status <> 'VERIFIED' AND verified_at IS NULL)
    )
);

COMMENT ON TABLE deploy_domain IS 'DNS Zone 下可验证、可绑定的 hostname 资源；不直接拥有应用或 TLS 配置';
COMMENT ON COLUMN deploy_domain.hostname_ascii IS '经 IDNA 规范化的小写 ASCII hostname';
COMMENT ON COLUMN deploy_domain.hostname_type IS 'EXACT 或 WILDCARD';
COMMENT ON COLUMN deploy_domain.verification_status IS '所有权验证状态';
COMMENT ON COLUMN deploy_domain.status IS 'hostname 管理生命周期状态';

CREATE UNIQUE INDEX uk_deploy_domain_active_hostname
    ON deploy_domain (hostname_ascii)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_deploy_domain_tenant_status
    ON deploy_domain (tenant_id, status, updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_deploy_domain_zone_updated
    ON deploy_domain (tenant_id, zone_id, updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_domain_verification (
    id                    BIGINT       NOT NULL,
    uuid                  VARCHAR(36)  NOT NULL,
    tenant_id             BIGINT       NOT NULL,
    domain_id             BIGINT       NOT NULL,
    method                VARCHAR(16)  NOT NULL,
    record_name           VARCHAR(253) NOT NULL,
    proof_sha256          VARCHAR(64)  NOT NULL,
    status                VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    observed_sha256       VARCHAR(64),
    verifier_identity     VARCHAR(128),
    attempt_count         INTEGER      NOT NULL DEFAULT 0,
    next_attempt_at       TIMESTAMPTZ,
    expires_at            TIMESTAMPTZ  NOT NULL,
    checked_at            TIMESTAMPTZ,
    verified_at           TIMESTAMPTZ,
    failure_code          VARCHAR(64),
    created_by            BIGINT,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version               BIGINT       NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_domain_verification_uuid UNIQUE (uuid),
    CONSTRAINT fk_deploy_domain_verification_domain FOREIGN KEY (domain_id) REFERENCES deploy_domain(id),
    CONSTRAINT chk_deploy_domain_verification_method CHECK (method IN ('DNS_TXT', 'DNS_CNAME', 'HTTP_FILE')),
    CONSTRAINT chk_deploy_domain_verification_status CHECK (status IN ('PENDING', 'CHECKING', 'VERIFIED', 'FAILED', 'EXPIRED')),
    CONSTRAINT chk_deploy_domain_verification_hash CHECK (
        proof_sha256 ~ '^[0-9a-f]{64}$'
        AND (observed_sha256 IS NULL OR observed_sha256 ~ '^[0-9a-f]{64}$')
    ),
    CONSTRAINT chk_deploy_domain_verification_attempts CHECK (attempt_count BETWEEN 0 AND 1000)
);

CREATE UNIQUE INDEX uk_deploy_domain_verification_active
    ON deploy_domain_verification (domain_id)
    WHERE status IN ('PENDING', 'CHECKING');

CREATE INDEX idx_deploy_domain_verification_due
    ON deploy_domain_verification (status, next_attempt_at, expires_at, id)
    WHERE status IN ('PENDING', 'CHECKING');

-- source: migrations/003_create_deploy_nginx_config.sql
-- Migration: 003_create_deploy_nginx_config
-- Description: 创建 Nginx 配置版本表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_nginx_config (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    site_id         BIGINT       NOT NULL,
    domain_id       BIGINT,
    config_type     INTEGER      NOT NULL DEFAULT 1,
    config_name     VARCHAR(200) NOT NULL,
    config_content  TEXT         NOT NULL,
    config_hash     VARCHAR(64)  NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT false,
    version_no      INTEGER      NOT NULL DEFAULT 1,
    deployed_at     TIMESTAMPTZ,
    status          INTEGER      NOT NULL DEFAULT 0,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_nginx_config_uuid UNIQUE (uuid),
    CONSTRAINT fk_deploy_nginx_config_site FOREIGN KEY (site_id) REFERENCES deploy_site(id)
);

COMMENT ON TABLE deploy_nginx_config IS 'Nginx配置版本表';
COMMENT ON COLUMN deploy_nginx_config.config_type IS '配置类型：1=站点，2=上游，3=SSL，4=自定义';
COMMENT ON COLUMN deploy_nginx_config.config_content IS 'Nginx配置内容';
COMMENT ON COLUMN deploy_nginx_config.config_hash IS '配置内容SHA-256哈希';
COMMENT ON COLUMN deploy_nginx_config.is_active IS '是否为当前活跃配置';
COMMENT ON COLUMN deploy_nginx_config.version_no IS '配置版本号';
COMMENT ON COLUMN deploy_nginx_config.deployed_at IS '部署时间';
COMMENT ON COLUMN deploy_nginx_config.status IS '状态：0=草稿，1=活跃，2=归档';

CREATE INDEX idx_deploy_nginx_config_site_active
    ON deploy_nginx_config (site_id, is_active);

CREATE INDEX idx_deploy_nginx_config_type_status
    ON deploy_nginx_config (config_type, status);

-- source: migrations/004_create_deploy_certificate.sql
-- Migration: 004_create_deploy_certificate
-- Description: 创建 SSL 证书表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_certificate (
    id                      BIGINT       NOT NULL,
    uuid                    VARCHAR(36)  NOT NULL,
    tenant_id               BIGINT       NOT NULL,
    organization_id         BIGINT       NOT NULL DEFAULT 0,
    cert_name               VARCHAR(200) NOT NULL,
    certificate_source      VARCHAR(16)  NOT NULL DEFAULT 'MANAGED',
    ca_profile              VARCHAR(32)  NOT NULL DEFAULT 'LETS_ENCRYPT_PRODUCTION',
    preferred_key_algorithm VARCHAR(16)  NOT NULL DEFAULT 'ECDSA',
    auto_renew              BOOLEAN      NOT NULL DEFAULT TRUE,
    renewal_status          VARCHAR(16)  NOT NULL DEFAULT 'NONE',
    status                  VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    idempotency_key         VARCHAR(128) NOT NULL,
    request_sha256          VARCHAR(64)  NOT NULL,
    metadata                JSONB        NOT NULL DEFAULT '{}',
    created_by              BIGINT,
    updated_by              BIGINT,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version                 BIGINT       NOT NULL DEFAULT 1,
    deleted_at              TIMESTAMPTZ,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_certificate_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_certificate_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT chk_deploy_certificate_source CHECK (certificate_source IN ('MANAGED', 'CUSTOM')),
    CONSTRAINT chk_deploy_certificate_ca_profile CHECK (ca_profile IN ('LETS_ENCRYPT_STAGING', 'LETS_ENCRYPT_PRODUCTION', 'CUSTOM')),
    CONSTRAINT chk_deploy_certificate_key_algorithm CHECK (preferred_key_algorithm IN ('RSA', 'ECDSA')),
    CONSTRAINT chk_deploy_certificate_renewal_status CHECK (renewal_status IN ('NONE', 'PLANNED', 'PROCESSING', 'FAILED')),
    CONSTRAINT chk_deploy_certificate_status CHECK (status IN ('PENDING', 'ISSUING', 'ACTIVE', 'EXPIRED', 'FAILED', 'REVOKED')),
    CONSTRAINT chk_deploy_certificate_request_hash CHECK (request_sha256 ~ '^[0-9a-f]{64}$')
);

COMMENT ON TABLE deploy_certificate IS 'TLS certificate lifecycle aggregate; hostname identifiers and immutable material versions are stored separately';
COMMENT ON COLUMN deploy_certificate.certificate_source IS 'MANAGED ACME lifecycle or CUSTOM secret-manager lifecycle';
COMMENT ON COLUMN deploy_certificate.preferred_key_algorithm IS 'Preferred issuance key algorithm; active RSA and ECDSA versions may coexist';

CREATE INDEX idx_deploy_certificate_renewal
    ON deploy_certificate (tenant_id, renewal_status, updated_at, id)
    WHERE auto_renew = TRUE AND status IN ('ACTIVE', 'FAILED') AND deleted_at IS NULL;

CREATE INDEX idx_deploy_certificate_tenant_updated
    ON deploy_certificate (tenant_id, updated_at DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_certificate_identifier (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(36)  NOT NULL,
    tenant_id       BIGINT       NOT NULL,
    certificate_id  BIGINT       NOT NULL,
    domain_id       BIGINT       NOT NULL,
    identifier_type VARCHAR(16)  NOT NULL,
    hostname_ascii  VARCHAR(253) NOT NULL,
    position        INTEGER      NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_certificate_identifier_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_certificate_identifier_name UNIQUE (certificate_id, hostname_ascii),
    CONSTRAINT uk_deploy_certificate_identifier_position UNIQUE (certificate_id, position),
    CONSTRAINT fk_deploy_certificate_identifier_certificate FOREIGN KEY (certificate_id) REFERENCES deploy_certificate(id),
    CONSTRAINT fk_deploy_certificate_identifier_domain FOREIGN KEY (domain_id) REFERENCES deploy_domain(id),
    CONSTRAINT chk_deploy_certificate_identifier_type CHECK (identifier_type IN ('EXACT', 'WILDCARD')),
    CONSTRAINT chk_deploy_certificate_identifier_position CHECK (position BETWEEN 0 AND 99)
);

CREATE INDEX idx_deploy_certificate_identifier_domain
    ON deploy_certificate_identifier (tenant_id, domain_id, certificate_id);

CREATE TABLE deploy_certificate_version (
    id                BIGINT       NOT NULL,
    uuid              VARCHAR(36)  NOT NULL,
    tenant_id         BIGINT       NOT NULL,
    certificate_id    BIGINT       NOT NULL,
    version_no        BIGINT       NOT NULL,
    serial_sha256     VARCHAR(64)  NOT NULL,
    fingerprint_sha256 VARCHAR(64) NOT NULL,
    spki_sha256       VARCHAR(64)  NOT NULL,
    chain_sha256      VARCHAR(64)  NOT NULL,
    issuer            VARCHAR(500) NOT NULL,
    subject           VARCHAR(500) NOT NULL,
    key_algorithm     VARCHAR(16)  NOT NULL,
    not_before        TIMESTAMPTZ  NOT NULL,
    not_after         TIMESTAMPTZ  NOT NULL,
    secret_bundle_ref VARCHAR(1024) NOT NULL,
    source_order_id   BIGINT,
    status            VARCHAR(16)  NOT NULL DEFAULT 'CANDIDATE',
    created_by        BIGINT,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_certificate_version_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_certificate_version_no UNIQUE (certificate_id, version_no),
    CONSTRAINT uk_deploy_certificate_version_fingerprint UNIQUE (tenant_id, fingerprint_sha256),
    CONSTRAINT fk_deploy_certificate_version_certificate FOREIGN KEY (certificate_id) REFERENCES deploy_certificate(id),
    CONSTRAINT chk_deploy_certificate_version_key_algorithm CHECK (key_algorithm IN ('RSA', 'ECDSA')),
    CONSTRAINT chk_deploy_certificate_version_status CHECK (status IN ('CANDIDATE', 'ACTIVE', 'SUPERSEDED', 'REVOKED', 'EXPIRED')),
    CONSTRAINT chk_deploy_certificate_version_validity CHECK (not_after > not_before),
    CONSTRAINT chk_deploy_certificate_version_hashes CHECK (
        serial_sha256 ~ '^[0-9a-f]{64}$'
        AND fingerprint_sha256 ~ '^[0-9a-f]{64}$'
        AND spki_sha256 ~ '^[0-9a-f]{64}$'
        AND chain_sha256 ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT chk_deploy_certificate_version_secret_ref CHECK (
        secret_bundle_ref LIKE 'secret://%' OR secret_bundle_ref LIKE 'file:%'
    )
);

CREATE INDEX idx_deploy_certificate_version_lifecycle
    ON deploy_certificate_version (tenant_id, status, not_after, id);

ALTER TABLE deploy_certificate
    ADD COLUMN desired_version_id BIGINT,
    ADD COLUMN current_version_id BIGINT,
    ADD CONSTRAINT fk_deploy_certificate_desired_version FOREIGN KEY (desired_version_id) REFERENCES deploy_certificate_version(id),
    ADD CONSTRAINT fk_deploy_certificate_current_version FOREIGN KEY (current_version_id) REFERENCES deploy_certificate_version(id);

-- source: migrations/005_create_deploy_deployment.sql
-- Migration: 005_create_deploy_deployment
-- Description: 创建部署记录表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_deployment (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    organization_id BIGINT       NOT NULL DEFAULT 0,
    user_id         BIGINT,
    site_id         BIGINT       NOT NULL,
    deploy_type     INTEGER      NOT NULL DEFAULT 1,
    version_tag     VARCHAR(100),
    commit_hash     VARCHAR(64),
    source_ref      VARCHAR(500),
    build_log       TEXT,
    deploy_log      TEXT,
    artifact_path   VARCHAR(500),
    artifact_size   BIGINT,
    artifact_hash   VARCHAR(64),
    environment     VARCHAR(32)  NOT NULL DEFAULT 'production',
    status          INTEGER      NOT NULL DEFAULT 0,
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    duration_ms     BIGINT,
    rollback_from   BIGINT,
    idempotency_key VARCHAR(200),
    request_id      VARCHAR(128),
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_deployment_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_deployment_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT fk_deploy_deployment_site FOREIGN KEY (site_id) REFERENCES deploy_site(id)
);

COMMENT ON TABLE deploy_deployment IS '部署记录表';
COMMENT ON COLUMN deploy_deployment.deploy_type IS '部署类型：1=上传，2=Git，3=CI/CD，4=API';
COMMENT ON COLUMN deploy_deployment.status IS '状态：0=待处理，1=构建中，2=部署中，3=成功，4=失败，5=已回滚';
COMMENT ON COLUMN deploy_deployment.duration_ms IS '部署耗时（毫秒）';
COMMENT ON COLUMN deploy_deployment.rollback_from IS '回滚来源部署ID';
COMMENT ON COLUMN deploy_deployment.idempotency_key IS '幂等键，租户内唯一';

CREATE INDEX idx_deploy_deployment_site_created
    ON deploy_deployment (site_id, created_at DESC);

CREATE INDEX idx_deploy_deployment_tenant_status
    ON deploy_deployment (tenant_id, status, created_at DESC);

CREATE INDEX idx_deploy_deployment_status
    ON deploy_deployment (status)
    WHERE status IN (0, 1, 2);

-- source: migrations/006_create_deploy_env_variable.sql
-- Migration: 006_create_deploy_env_variable
-- Description: 创建环境变量表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_env_variable (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    site_id         BIGINT       NOT NULL,
    environment     VARCHAR(32)  NOT NULL DEFAULT 'production',
    key             VARCHAR(200) NOT NULL,
    value_encrypted TEXT         NOT NULL,
    is_secret       BOOLEAN      NOT NULL DEFAULT true,
    status          INTEGER      NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_env_variable_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_env_variable_key UNIQUE (site_id, environment, key)
);

COMMENT ON TABLE deploy_env_variable IS '环境变量表';
COMMENT ON COLUMN deploy_env_variable.key IS '变量名';
COMMENT ON COLUMN deploy_env_variable.value_encrypted IS '加密存储的变量值';
COMMENT ON COLUMN deploy_env_variable.is_secret IS '是否为密钥类型';
COMMENT ON COLUMN deploy_env_variable.environment IS '所属环境';

CREATE INDEX idx_deploy_env_variable_site_env
    ON deploy_env_variable (site_id, environment);

-- source: migrations/007_create_deploy_health_check.sql
-- Migration: 007_create_deploy_health_check
-- Description: 创建健康检查配置表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_health_check (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    site_id         BIGINT       NOT NULL,
    domain_id       BIGINT,
    check_type      INTEGER      NOT NULL DEFAULT 1,
    check_url       VARCHAR(2000),
    check_interval  INTEGER      NOT NULL DEFAULT 60,
    timeout_ms      INTEGER      NOT NULL DEFAULT 5000,
    retry_count     INTEGER      NOT NULL DEFAULT 3,
    expected_status INTEGER,
    expected_body   VARCHAR(500),
    status          INTEGER      NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_health_check_uuid UNIQUE (uuid),
    CONSTRAINT fk_deploy_health_check_site FOREIGN KEY (site_id) REFERENCES deploy_site(id)
);

COMMENT ON TABLE deploy_health_check IS '健康检查配置表';
COMMENT ON COLUMN deploy_health_check.check_type IS '检查类型：1=HTTP，2=TCP，3=Ping';
COMMENT ON COLUMN deploy_health_check.check_interval IS '检查间隔（秒）';
COMMENT ON COLUMN deploy_health_check.timeout_ms IS '超时时间（毫秒）';
COMMENT ON COLUMN deploy_health_check.retry_count IS '重试次数';

CREATE INDEX idx_deploy_health_check_site
    ON deploy_health_check (site_id);

-- source: migrations/008_create_deploy_health_result.sql
-- Migration: 008_create_deploy_health_result
-- Description: 创建健康检查结果表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_health_result (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    health_check_id BIGINT       NOT NULL,
    site_id         BIGINT       NOT NULL,
    is_healthy      BOOLEAN      NOT NULL,
    response_ms     INTEGER,
    status_code     INTEGER,
    error_message   VARCHAR(1000),
    checked_at      TIMESTAMPTZ  NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE deploy_health_result IS '健康检查结果表';
COMMENT ON COLUMN deploy_health_result.is_healthy IS '是否健康';
COMMENT ON COLUMN deploy_health_result.response_ms IS '响应时间（毫秒）';
COMMENT ON COLUMN deploy_health_result.status_code IS 'HTTP状态码';
COMMENT ON COLUMN deploy_health_result.checked_at IS '检查时间';

CREATE INDEX idx_deploy_health_result_check_time
    ON deploy_health_result (health_check_id, checked_at DESC);

CREATE INDEX idx_deploy_health_result_site_time
    ON deploy_health_result (site_id, checked_at DESC);

-- source: migrations/009_create_deploy_audit_log.sql
-- Migration: 009_create_deploy_audit_log
-- Description: 创建操作审计日志表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_audit_log (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    organization_id BIGINT       NOT NULL DEFAULT 0,
    operator_id     BIGINT       NOT NULL,
    operator_type   VARCHAR(32)  NOT NULL DEFAULT 'USER',
    action          VARCHAR(100) NOT NULL,
    target_type     VARCHAR(100) NOT NULL,
    target_id       BIGINT,
    target_uuid     VARCHAR(64),
    request_id      VARCHAR(128),
    ip_address      VARCHAR(45),
    user_agent      VARCHAR(500),
    changes         JSONB,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE deploy_audit_log IS '操作审计日志表';
COMMENT ON COLUMN deploy_audit_log.operator_id IS '操作人ID';
COMMENT ON COLUMN deploy_audit_log.operator_type IS '操作人类型：USER, SYSTEM, ADMIN, JOB, SERVICE';
COMMENT ON COLUMN deploy_audit_log.action IS '操作类型';
COMMENT ON COLUMN deploy_audit_log.target_type IS '目标对象类型';
COMMENT ON COLUMN deploy_audit_log.target_id IS '目标对象ID';
COMMENT ON COLUMN deploy_audit_log.changes IS '变更内容JSON：{"field": {"old": x, "new": y}}';

CREATE INDEX idx_deploy_audit_log_target
    ON deploy_audit_log (target_type, target_id, created_at DESC);

CREATE INDEX idx_deploy_audit_log_operator
    ON deploy_audit_log (operator_id, created_at DESC);

CREATE INDEX idx_deploy_audit_log_tenant_action
    ON deploy_audit_log (tenant_id, action, created_at DESC);

-- source: migrations/010_create_deploy_server.sql
-- Migration: 010_create_deploy_server
-- Description: 创建后端部署服务器表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-23

CREATE TABLE deploy_server (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    name            VARCHAR(200) NOT NULL,
    host            VARCHAR(255) NOT NULL,
    ssh_port        INTEGER      NOT NULL DEFAULT 22,
    status          INTEGER      NOT NULL DEFAULT 0,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_server_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_server_host UNIQUE (tenant_id, host)
);

COMMENT ON TABLE deploy_server IS '部署后端服务器表';
COMMENT ON COLUMN deploy_server.status IS '状态：0=未连接，1=在线，2=离线，3=维护中';

CREATE INDEX idx_deploy_server_tenant_status
    ON deploy_server (tenant_id, status, updated_at DESC);

-- folded migration: migrations/postgres/0001_deploy_upload_session_ref.up.sql
-- deploy upload session references (Drive-backed artifact lifecycle)
CREATE TABLE IF NOT EXISTS deploy_upload_session_ref (
    id BIGINT PRIMARY KEY NOT NULL,
    uuid VARCHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    site_id BIGINT NULL,
    drive_upload_session_id VARCHAR(128) NOT NULL,
    drive_upload_item_id VARCHAR(128) NULL,
    drive_space_id VARCHAR(128) NULL,
    drive_node_id VARCHAR(128) NULL,
    package_type INTEGER NOT NULL,
    file_name VARCHAR(500) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    content_length BIGINT NOT NULL,
    checksum VARCHAR(128) NULL,
    status INTEGER NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_upload_session_ref_uuid
    ON deploy_upload_session_ref (uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_upload_session_ref_idempotency
    ON deploy_upload_session_ref (tenant_id, idempotency_key)
    WHERE deleted_at IS NULL;

-- folded migration: migrations/postgres/0002_deploy_certificate_idempotency_key.up.sql
ALTER TABLE deploy_certificate
    ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(128);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_certificate_idempotency
    ON deploy_certificate (tenant_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

-- folded migration: migrations/postgres/0003_deploy_artifact_release.up.sql
-- Immutable artifacts from completed package upload sessions
CREATE TABLE IF NOT EXISTS deploy_artifact (
    id BIGINT PRIMARY KEY NOT NULL,
    uuid VARCHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    site_id BIGINT NULL,
    upload_session_ref_id BIGINT NOT NULL,
    package_type INTEGER NOT NULL,
    file_name VARCHAR(500) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    content_length BIGINT NOT NULL,
    checksum_sha256 VARCHAR(128) NULL,
    drive_node_id VARCHAR(128) NOT NULL,
    drive_space_id VARCHAR(128) NULL,
    drive_path VARCHAR(500) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_deploy_artifact_upload_session
        FOREIGN KEY (upload_session_ref_id) REFERENCES deploy_upload_session_ref(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_artifact_uuid
    ON deploy_artifact (uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_artifact_upload_session
    ON deploy_artifact (upload_session_ref_id);

CREATE INDEX IF NOT EXISTS idx_deploy_artifact_tenant_created
    ON deploy_artifact (tenant_id, created_at DESC);

-- Immutable site releases referencing one artifact
CREATE TABLE IF NOT EXISTS deploy_release (
    id BIGINT PRIMARY KEY NOT NULL,
    uuid VARCHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    site_id BIGINT NOT NULL,
    artifact_id BIGINT NOT NULL,
    version_tag VARCHAR(100) NULL,
    status INTEGER NOT NULL DEFAULT 1,
    idempotency_key VARCHAR(128) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_deploy_release_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT fk_deploy_release_artifact FOREIGN KEY (artifact_id) REFERENCES deploy_artifact(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_release_uuid
    ON deploy_release (uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_release_idempotency
    ON deploy_release (tenant_id, site_id, idempotency_key);

CREATE INDEX IF NOT EXISTS idx_deploy_release_site_created
    ON deploy_release (site_id, created_at DESC);

ALTER TABLE deploy_deployment
    ADD COLUMN IF NOT EXISTS release_id BIGINT NULL;

CREATE INDEX IF NOT EXISTS idx_deploy_deployment_release
    ON deploy_deployment (release_id)
    WHERE release_id IS NOT NULL;

-- Live website composition. Provider UUIDs are opaque owner-service identities; source content
-- versions, object keys, URLs, and credentials never enter these configuration tables.
CREATE TABLE deploy_site_resource (
    id                        BIGINT PRIMARY KEY NOT NULL,
    uuid                      VARCHAR(36) NOT NULL,
    tenant_id                 BIGINT NOT NULL,
    organization_id           BIGINT NOT NULL DEFAULT 0,
    site_id                   BIGINT NOT NULL,
    resource_key              VARCHAR(64) NOT NULL,
    provider_type             VARCHAR(32) NOT NULL,
    provider_resource_uuid    VARCHAR(128) NOT NULL,
    provider_contract_version VARCHAR(64) NOT NULL,
    capabilities_json         JSONB NOT NULL DEFAULT '{}',
    status                    VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    last_validated_at         TIMESTAMPTZ NULL,
    last_error_code           VARCHAR(64) NULL,
    metadata                  JSONB NOT NULL DEFAULT '{}',
    created_by                BIGINT NULL,
    updated_by                BIGINT NULL,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version                   BIGINT NOT NULL DEFAULT 1,
    deleted_at                TIMESTAMPTZ NULL,
    CONSTRAINT uk_deploy_site_resource_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_resource_key UNIQUE (site_id, resource_key),
    CONSTRAINT fk_deploy_site_resource_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT chk_deploy_site_resource_provider CHECK (provider_type IN ('DRIVE', 'KNOWLEDGEBASE')),
    CONSTRAINT chk_deploy_site_resource_status CHECK (status IN ('PENDING', 'VALID', 'INVALID', 'UNAVAILABLE', 'REVOKED'))
);

CREATE INDEX idx_deploy_site_resource_site_status
    ON deploy_site_resource (tenant_id, site_id, status)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_deploy_site_resource_provider
    ON deploy_site_resource (tenant_id, provider_type, provider_resource_uuid)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_site_variant (
    id              BIGINT PRIMARY KEY NOT NULL,
    uuid            VARCHAR(36) NOT NULL,
    tenant_id       BIGINT NOT NULL,
    site_id         BIGINT NOT NULL,
    variant_key     VARCHAR(64) NOT NULL,
    label           VARCHAR(64) NOT NULL,
    client_class    VARCHAR(16) NOT NULL DEFAULT 'OTHER',
    is_default      BOOLEAN NOT NULL DEFAULT FALSE,
    priority        INTEGER NOT NULL DEFAULT 0,
    status          VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    metadata        JSONB NOT NULL DEFAULT '{}',
    created_by      BIGINT NULL,
    updated_by      BIGINT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version         BIGINT NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMPTZ NULL,
    CONSTRAINT uk_deploy_site_variant_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_variant_key UNIQUE (site_id, variant_key),
    CONSTRAINT fk_deploy_site_variant_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT chk_deploy_site_variant_client CHECK (client_class IN ('DESKTOP', 'MOBILE', 'TABLET', 'TV', 'BOT', 'OTHER')),
    CONSTRAINT chk_deploy_site_variant_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE UNIQUE INDEX uk_deploy_site_variant_default
    ON deploy_site_variant (site_id)
    WHERE is_default = TRUE AND status = 'ACTIVE' AND deleted_at IS NULL;

CREATE INDEX idx_deploy_site_variant_site_priority
    ON deploy_site_variant (tenant_id, site_id, status, priority, uuid)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_site_variant_rule (
    id                BIGINT PRIMARY KEY NOT NULL,
    uuid              VARCHAR(36) NOT NULL,
    tenant_id         BIGINT NOT NULL,
    site_id           BIGINT NOT NULL,
    rule_key          VARCHAR(64) NOT NULL,
    target_variant_id BIGINT NOT NULL,
    rule_type         VARCHAR(16) NOT NULL,
    match_value       VARCHAR(4096) NOT NULL,
    priority          INTEGER NOT NULL DEFAULT 0,
    status            VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_by        BIGINT NULL,
    updated_by        BIGINT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version           BIGINT NOT NULL DEFAULT 1,
    deleted_at        TIMESTAMPTZ NULL,
    CONSTRAINT uk_deploy_site_variant_rule_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_variant_rule_key UNIQUE (site_id, rule_key),
    CONSTRAINT fk_deploy_site_variant_rule_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT fk_deploy_site_variant_rule_variant FOREIGN KEY (target_variant_id) REFERENCES deploy_site_variant(id),
    CONSTRAINT chk_deploy_site_variant_rule_type CHECK (rule_type IN ('PATH_PREFIX', 'CLIENT_CLASS')),
    CONSTRAINT chk_deploy_site_variant_rule_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT chk_deploy_site_variant_rule_priority CHECK (priority BETWEEN 0 AND 65535)
);

CREATE INDEX idx_deploy_site_variant_rule_order
    ON deploy_site_variant_rule (tenant_id, site_id, status, priority, uuid)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_site_mount (
    id                BIGINT PRIMARY KEY NOT NULL,
    uuid              VARCHAR(36) NOT NULL,
    tenant_id         BIGINT NOT NULL,
    site_id           BIGINT NOT NULL,
    mount_key         VARCHAR(64) NOT NULL,
    variant_id        BIGINT NOT NULL,
    resource_id       BIGINT NOT NULL,
    path_prefix       VARCHAR(4096) NOT NULL,
    resource_subpath  VARCHAR(4096) NOT NULL DEFAULT '/',
    mount_mode        VARCHAR(16) NOT NULL DEFAULT 'ROOT',
    handler_type      VARCHAR(16) NOT NULL,
    index_files_json  JSONB NOT NULL DEFAULT '[]',
    spa_fallback_path VARCHAR(4096) NULL,
    priority          INTEGER NOT NULL DEFAULT 0,
    status            VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_by        BIGINT NULL,
    updated_by        BIGINT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version           BIGINT NOT NULL DEFAULT 1,
    deleted_at        TIMESTAMPTZ NULL,
    CONSTRAINT uk_deploy_site_mount_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_mount_key UNIQUE (site_id, mount_key),
    CONSTRAINT uk_deploy_site_mount_prefix UNIQUE (variant_id, path_prefix),
    CONSTRAINT fk_deploy_site_mount_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT fk_deploy_site_mount_variant FOREIGN KEY (variant_id) REFERENCES deploy_site_variant(id),
    CONSTRAINT fk_deploy_site_mount_resource FOREIGN KEY (resource_id) REFERENCES deploy_site_resource(id),
    CONSTRAINT chk_deploy_site_mount_mode CHECK (mount_mode IN ('ROOT', 'ALIAS')),
    CONSTRAINT chk_deploy_site_mount_handler CHECK (handler_type IN ('STATIC', 'SPA', 'WIKI')),
    CONSTRAINT chk_deploy_site_mount_status CHECK (status IN ('ACTIVE', 'DISABLED', 'INVALID'))
);

CREATE INDEX idx_deploy_site_mount_route
    ON deploy_site_mount (tenant_id, site_id, variant_id, status, path_prefix)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_site_binding (
    id                   BIGINT PRIMARY KEY NOT NULL,
    uuid                 VARCHAR(36) NOT NULL,
    tenant_id            BIGINT NOT NULL,
    organization_id      BIGINT NOT NULL DEFAULT 0,
    site_id              BIGINT NOT NULL,
    binding_key           VARCHAR(64) NOT NULL,
    domain_id            BIGINT NOT NULL,
    hostname_ascii       VARCHAR(255) NOT NULL,
    environment          VARCHAR(16) NOT NULL,
    path_prefix          VARCHAR(4096) NOT NULL DEFAULT '/',
    action_type          VARCHAR(16) NOT NULL DEFAULT 'SERVE',
    is_canonical         BOOLEAN NOT NULL DEFAULT FALSE,
    default_variant_id   BIGINT NULL,
    forced_variant_id    BIGINT NULL,
    redirect_scheme      VARCHAR(8) NULL,
    redirect_hostname    VARCHAR(255) NULL,
    redirect_path_prefix VARCHAR(4096) NULL,
    redirect_status_code INTEGER NULL,
    preserve_path        BOOLEAN NOT NULL DEFAULT TRUE,
    preserve_query       BOOLEAN NOT NULL DEFAULT TRUE,
    status               VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    verified_at          TIMESTAMPTZ NULL,
    activated_at         TIMESTAMPTZ NULL,
    created_by           BIGINT NULL,
    updated_by           BIGINT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version              BIGINT NOT NULL DEFAULT 1,
    deleted_at           TIMESTAMPTZ NULL,
    CONSTRAINT uk_deploy_site_binding_uuid UNIQUE (uuid),
    CONSTRAINT fk_deploy_site_binding_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT fk_deploy_site_binding_domain FOREIGN KEY (domain_id) REFERENCES deploy_domain(id),
    CONSTRAINT fk_deploy_site_binding_default_variant FOREIGN KEY (default_variant_id) REFERENCES deploy_site_variant(id),
    CONSTRAINT fk_deploy_site_binding_forced_variant FOREIGN KEY (forced_variant_id) REFERENCES deploy_site_variant(id),
    CONSTRAINT chk_deploy_site_binding_environment CHECK (environment IN ('development', 'test', 'staging', 'production')),
    CONSTRAINT chk_deploy_site_binding_action CHECK (action_type IN ('SERVE', 'REDIRECT')),
    CONSTRAINT chk_deploy_site_binding_status CHECK (status IN ('PENDING', 'VERIFIED', 'ACTIVE', 'PAUSED', 'FAILED', 'ARCHIVED')),
    CONSTRAINT chk_deploy_site_binding_redirect_status CHECK (redirect_status_code IS NULL OR redirect_status_code IN (301, 302, 307, 308))
);

CREATE INDEX idx_deploy_site_binding_site_status
    ON deploy_site_binding (tenant_id, site_id, environment, status)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uk_deploy_site_binding_active_key
    ON deploy_site_binding (site_id, binding_key)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uk_deploy_site_binding_active_route
    ON deploy_site_binding (hostname_ascii, path_prefix, environment)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uk_deploy_site_binding_canonical
    ON deploy_site_binding (site_id, environment)
    WHERE is_canonical = TRUE AND status = 'ACTIVE' AND deleted_at IS NULL;

CREATE TABLE deploy_tls_policy (
    id                    BIGINT       NOT NULL,
    uuid                  VARCHAR(36)  NOT NULL,
    tenant_id             BIGINT       NOT NULL,
    site_binding_id       BIGINT       NOT NULL,
    certificate_source    VARCHAR(16)  NOT NULL DEFAULT 'MANAGED',
    challenge_method      VARCHAR(16)  NOT NULL DEFAULT 'AUTO',
    minimum_tls_version   VARCHAR(8)   NOT NULL DEFAULT 'TLS1.2',
    maximum_tls_version   VARCHAR(8)   NOT NULL DEFAULT 'TLS1.3',
    alpn_json             JSONB        NOT NULL DEFAULT '["h2","http/1.1"]',
    auto_renew            BOOLEAN      NOT NULL DEFAULT TRUE,
    renew_before_days     INTEGER      NOT NULL DEFAULT 30,
    activation_quorum     INTEGER      NOT NULL DEFAULT 100,
    status                VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_by            BIGINT,
    updated_by            BIGINT,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version               BIGINT       NOT NULL DEFAULT 1,
    deleted_at            TIMESTAMPTZ,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_tls_policy_uuid UNIQUE (uuid),
    CONSTRAINT fk_deploy_tls_policy_binding FOREIGN KEY (site_binding_id) REFERENCES deploy_site_binding(id),
    CONSTRAINT chk_deploy_tls_policy_source CHECK (certificate_source IN ('MANAGED', 'CUSTOM', 'EXTERNAL')),
    CONSTRAINT chk_deploy_tls_policy_challenge CHECK (challenge_method IN ('AUTO', 'HTTP_01', 'DNS_01')),
    CONSTRAINT chk_deploy_tls_policy_versions CHECK (
        minimum_tls_version IN ('TLS1.2', 'TLS1.3')
        AND maximum_tls_version IN ('TLS1.2', 'TLS1.3')
        AND minimum_tls_version <= maximum_tls_version
    ),
    CONSTRAINT chk_deploy_tls_policy_renewal CHECK (renew_before_days BETWEEN 14 AND 90),
    CONSTRAINT chk_deploy_tls_policy_quorum CHECK (activation_quorum BETWEEN 1 AND 100),
    CONSTRAINT chk_deploy_tls_policy_status CHECK (status IN ('ACTIVE', 'PAUSED', 'ARCHIVED'))
);

CREATE UNIQUE INDEX uk_deploy_tls_policy_active_binding
    ON deploy_tls_policy (site_binding_id)
    WHERE status = 'ACTIVE' AND deleted_at IS NULL;

CREATE TABLE deploy_listener_certificate_binding (
    id                    BIGINT      NOT NULL,
    uuid                  VARCHAR(36) NOT NULL,
    tenant_id             BIGINT      NOT NULL,
    site_binding_id       BIGINT      NOT NULL,
    certificate_id        BIGINT      NOT NULL,
    certificate_version_id BIGINT,
    key_algorithm         VARCHAR(16) NOT NULL,
    priority              INTEGER     NOT NULL DEFAULT 100,
    is_default            BOOLEAN     NOT NULL DEFAULT FALSE,
    status                VARCHAR(16) NOT NULL DEFAULT 'CANDIDATE',
    activated_at          TIMESTAMPTZ,
    created_by            BIGINT,
    updated_by            BIGINT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version               BIGINT      NOT NULL DEFAULT 1,
    deleted_at            TIMESTAMPTZ,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_listener_certificate_binding_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_listener_certificate_binding_certificate UNIQUE (site_binding_id, certificate_id),
    CONSTRAINT fk_deploy_listener_certificate_binding_route FOREIGN KEY (site_binding_id) REFERENCES deploy_site_binding(id),
    CONSTRAINT fk_deploy_listener_certificate_binding_certificate FOREIGN KEY (certificate_id) REFERENCES deploy_certificate(id),
    CONSTRAINT fk_deploy_listener_certificate_binding_version FOREIGN KEY (certificate_version_id) REFERENCES deploy_certificate_version(id),
    CONSTRAINT chk_deploy_listener_certificate_binding_algorithm CHECK (key_algorithm IN ('RSA', 'ECDSA')),
    CONSTRAINT chk_deploy_listener_certificate_binding_priority CHECK (priority BETWEEN 0 AND 10000),
    CONSTRAINT chk_deploy_listener_certificate_binding_status CHECK (status IN ('CANDIDATE', 'ACTIVE', 'PAUSED', 'FAILED', 'ARCHIVED'))
);

CREATE UNIQUE INDEX uk_deploy_listener_certificate_binding_active_algorithm
    ON deploy_listener_certificate_binding (site_binding_id, key_algorithm)
    WHERE status = 'ACTIVE' AND deleted_at IS NULL;

CREATE INDEX idx_deploy_listener_certificate_binding_certificate
    ON deploy_listener_certificate_binding (tenant_id, certificate_id, status)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_site_revision (
    id                        BIGINT PRIMARY KEY NOT NULL,
    uuid                      VARCHAR(36) NOT NULL,
    tenant_id                 BIGINT NOT NULL,
    organization_id           BIGINT NOT NULL DEFAULT 0,
    site_id                   BIGINT NOT NULL,
    revision_no               BIGINT NOT NULL,
    environment               VARCHAR(16) NOT NULL,
    descriptor_schema_version VARCHAR(64) NOT NULL,
    descriptor_json           JSONB NOT NULL,
    descriptor_sha256         VARCHAR(64) NOT NULL,
    compiler_version          VARCHAR(128) NOT NULL,
    source_config_version     BIGINT NOT NULL,
    idempotency_key           VARCHAR(128) NOT NULL,
    request_sha256            VARCHAR(64) NOT NULL,
    result_json               JSONB NOT NULL DEFAULT '{}',
    validation_status         VARCHAR(16) NOT NULL DEFAULT 'VALID',
    validation_report_json    JSONB NOT NULL DEFAULT '{}',
    supersedes_revision_id    BIGINT NULL,
    created_by                BIGINT NULL,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_deploy_site_revision_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_revision_no UNIQUE (site_id, revision_no),
    CONSTRAINT uk_deploy_site_revision_hash UNIQUE (site_id, descriptor_sha256),
    CONSTRAINT uk_deploy_site_revision_idempotency UNIQUE (tenant_id, site_id, idempotency_key),
    CONSTRAINT fk_deploy_site_revision_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT fk_deploy_site_revision_supersedes FOREIGN KEY (supersedes_revision_id) REFERENCES deploy_site_revision(id),
    CONSTRAINT chk_deploy_site_revision_environment CHECK (environment IN ('development', 'test', 'staging', 'production')),
    CONSTRAINT chk_deploy_site_revision_validation CHECK (validation_status IN ('VALID', 'INVALID'))
);

CREATE INDEX idx_deploy_site_revision_site_created
    ON deploy_site_revision (tenant_id, site_id, revision_no DESC);

CREATE TABLE deploy_web_node_target (
    id                BIGINT PRIMARY KEY NOT NULL,
    uuid              VARCHAR(36) NOT NULL,
    tenant_id         BIGINT NOT NULL,
    node_uuid         VARCHAR(128) NOT NULL,
    environment       VARCHAR(16) NOT NULL,
    tenant_scope_hash VARCHAR(64) NOT NULL,
    region            VARCHAR(64) NULL,
    status            VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version           BIGINT NOT NULL DEFAULT 1,
    deleted_at        TIMESTAMPTZ NULL,
    CONSTRAINT uk_deploy_web_node_target_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_web_node_target_node UNIQUE (node_uuid, environment),
    CONSTRAINT chk_deploy_web_node_target_environment CHECK (environment IN ('development', 'test', 'staging', 'production')),
    CONSTRAINT chk_deploy_web_node_target_status CHECK (status IN ('ACTIVE', 'DRAINING', 'DISABLED'))
);

CREATE INDEX idx_deploy_web_node_target_tenant
    ON deploy_web_node_target (tenant_id, environment, status, node_uuid)
    WHERE deleted_at IS NULL;

-- Durable desired-state/outbox row. Web Server owns the delivery projection and Node observation;
-- Deployments retains the exact bytes and publication result needed for idempotent reconciliation.
CREATE TABLE deploy_runtime_assignment (
    id                     BIGINT PRIMARY KEY NOT NULL,
    uuid                   VARCHAR(36) NOT NULL,
    tenant_id              BIGINT NOT NULL,
    node_target_id         BIGINT NOT NULL,
    trigger_site_revision_id BIGINT NULL,
    generation             BIGINT NOT NULL,
    snapshot_uuid          VARCHAR(128) NOT NULL,
    snapshot_sha256        VARCHAR(64) NOT NULL,
    desired_state_sha256   VARCHAR(64) NOT NULL,
    runtime_set_json       JSONB NOT NULL,
    runtime_set_bytes      BIGINT NOT NULL,
    publish_status         VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    remote_assignment_uuid VARCHAR(128) NULL,
    attempt_count          INTEGER NOT NULL DEFAULT 0,
    next_attempt_at        TIMESTAMPTZ NULL,
    lease_owner            VARCHAR(128) NULL,
    lease_expires_at       TIMESTAMPTZ NULL,
    last_error_code        VARCHAR(64) NULL,
    published_at           TIMESTAMPTZ NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version                BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT uk_deploy_runtime_assignment_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_runtime_assignment_generation UNIQUE (node_target_id, generation),
    CONSTRAINT uk_deploy_runtime_assignment_snapshot UNIQUE (snapshot_uuid),
    CONSTRAINT fk_deploy_runtime_assignment_target FOREIGN KEY (node_target_id) REFERENCES deploy_web_node_target(id),
    CONSTRAINT fk_deploy_runtime_assignment_revision FOREIGN KEY (trigger_site_revision_id) REFERENCES deploy_site_revision(id),
    CONSTRAINT chk_deploy_runtime_assignment_generation CHECK (generation BETWEEN 1 AND 9007199254740991),
    CONSTRAINT chk_deploy_runtime_assignment_bytes CHECK (runtime_set_bytes > 0 AND runtime_set_bytes <= 67108864),
    CONSTRAINT chk_deploy_runtime_assignment_status CHECK (publish_status IN ('PENDING', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'SUPERSEDED')),
    CONSTRAINT chk_deploy_runtime_assignment_lease CHECK (
        (publish_status = 'PUBLISHING' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
        OR (publish_status <> 'PUBLISHING' AND lease_owner IS NULL AND lease_expires_at IS NULL)
    )
);

CREATE INDEX idx_deploy_runtime_assignment_delivery
    ON deploy_runtime_assignment (publish_status, next_attempt_at, lease_expires_at, created_at)
    WHERE publish_status IN ('PENDING', 'PUBLISHING', 'FAILED');

CREATE INDEX idx_deploy_runtime_assignment_target_latest
    ON deploy_runtime_assignment (tenant_id, node_target_id, generation DESC);

-- Authenticated, append-only evidence read from the Web-owned runtime observation API.
CREATE TABLE deploy_site_target_observation (
    id                       BIGINT PRIMARY KEY NOT NULL,
    uuid                     VARCHAR(36) NOT NULL,
    tenant_id                BIGINT NOT NULL,
    site_id                  BIGINT NULL,
    site_revision_id         BIGINT NULL,
    node_target_id           BIGINT NOT NULL,
    runtime_assignment_id    BIGINT NOT NULL,
    remote_observation_uuid  VARCHAR(128) NOT NULL,
    remote_assignment_uuid   VARCHAR(128) NOT NULL,
    generation               BIGINT NOT NULL,
    snapshot_uuid            VARCHAR(128) NOT NULL,
    snapshot_sha256          VARCHAR(64) NOT NULL,
    environment              VARCHAR(16) NOT NULL,
    state                    VARCHAR(16) NOT NULL,
    node_version             VARCHAR(64) NULL,
    reason_code              VARCHAR(64) NULL,
    detail                   VARCHAR(512) NULL,
    observed_at              TIMESTAMPTZ NOT NULL,
    ingested_at              TIMESTAMPTZ NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_deploy_site_target_observation_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_target_observation_remote UNIQUE (remote_observation_uuid),
    CONSTRAINT uk_deploy_site_target_observation_state UNIQUE (runtime_assignment_id, state),
    CONSTRAINT fk_deploy_site_target_observation_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT fk_deploy_site_target_observation_revision FOREIGN KEY (site_revision_id) REFERENCES deploy_site_revision(id),
    CONSTRAINT fk_deploy_site_target_observation_target FOREIGN KEY (node_target_id) REFERENCES deploy_web_node_target(id),
    CONSTRAINT fk_deploy_site_target_observation_assignment FOREIGN KEY (runtime_assignment_id) REFERENCES deploy_runtime_assignment(id),
    CONSTRAINT chk_deploy_site_target_observation_site_pair CHECK (
        (site_id IS NULL AND site_revision_id IS NULL)
        OR (site_id IS NOT NULL AND site_revision_id IS NOT NULL)
    ),
    CONSTRAINT chk_deploy_site_target_observation_generation CHECK (generation BETWEEN 1 AND 9007199254740991),
    CONSTRAINT chk_deploy_site_target_observation_snapshot_sha256 CHECK (snapshot_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_deploy_site_target_observation_environment CHECK (environment IN ('development', 'test', 'staging', 'production')),
    CONSTRAINT chk_deploy_site_target_observation_state CHECK (state IN ('RECEIVED', 'VALIDATED', 'STAGED', 'ACTIVE', 'REJECTED')),
    CONSTRAINT chk_deploy_site_target_observation_reason CHECK (
        (state = 'REJECTED' AND reason_code IS NOT NULL)
        OR (state <> 'REJECTED' AND reason_code IS NULL AND detail IS NULL)
    )
);

CREATE INDEX idx_deploy_site_target_observation_rollout
    ON deploy_site_target_observation (tenant_id, site_revision_id, state, node_target_id);

CREATE INDEX idx_deploy_site_target_observation_assignment
    ON deploy_site_target_observation (runtime_assignment_id, id DESC);

CREATE TABLE deploy_acme_account (
    id                 BIGINT        NOT NULL,
    uuid               VARCHAR(36)   NOT NULL,
    tenant_id          BIGINT        NOT NULL,
    ca_profile         VARCHAR(32)   NOT NULL,
    directory_url      VARCHAR(2048) NOT NULL,
    contact_email      VARCHAR(320)  NOT NULL,
    external_account_digest VARCHAR(64),
    account_key_secret_ref VARCHAR(1024) NOT NULL,
    status             VARCHAR(16)   NOT NULL DEFAULT 'ACTIVE',
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    version            BIGINT        NOT NULL DEFAULT 1,
    deleted_at         TIMESTAMPTZ,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_acme_account_uuid UNIQUE (uuid),
    CONSTRAINT chk_deploy_acme_account_profile CHECK (ca_profile IN ('LETS_ENCRYPT_STAGING', 'LETS_ENCRYPT_PRODUCTION')),
    CONSTRAINT chk_deploy_acme_account_status CHECK (status IN ('ACTIVE', 'DISABLED', 'INVALID')),
    CONSTRAINT chk_deploy_acme_account_secret_ref CHECK (account_key_secret_ref LIKE 'secret://%'),
    CONSTRAINT chk_deploy_acme_account_external_digest CHECK (
        external_account_digest IS NULL OR external_account_digest ~ '^[0-9a-f]{64}$'
    )
);

CREATE UNIQUE INDEX uk_deploy_acme_account_tenant_profile_email
    ON deploy_acme_account (tenant_id, ca_profile, contact_email)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_certificate_order (
    id                    BIGINT       NOT NULL,
    uuid                  VARCHAR(36)  NOT NULL,
    tenant_id             BIGINT       NOT NULL,
    certificate_id        BIGINT       NOT NULL,
    acme_account_id       BIGINT       NOT NULL,
    requested_version_no  BIGINT       NOT NULL,
    request_sha256        VARCHAR(64)  NOT NULL,
    idempotency_key       VARCHAR(128) NOT NULL,
    external_order_digest VARCHAR(64),
    status                VARCHAR(32)  NOT NULL DEFAULT 'REQUESTED',
    attempt_count         INTEGER      NOT NULL DEFAULT 0,
    next_attempt_at       TIMESTAMPTZ,
    lease_owner           VARCHAR(128),
    lease_expires_at      TIMESTAMPTZ,
    deadline_at           TIMESTAMPTZ  NOT NULL,
    last_error_code       VARCHAR(64),
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version               BIGINT       NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_certificate_order_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_certificate_order_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT uk_deploy_certificate_order_version UNIQUE (certificate_id, requested_version_no),
    CONSTRAINT fk_deploy_certificate_order_certificate FOREIGN KEY (certificate_id) REFERENCES deploy_certificate(id),
    CONSTRAINT fk_deploy_certificate_order_account FOREIGN KEY (acme_account_id) REFERENCES deploy_acme_account(id),
    CONSTRAINT chk_deploy_certificate_order_status CHECK (status IN (
        'REQUESTED', 'ACCOUNT_READY', 'ORDER_PENDING', 'CHALLENGE_PRESENTING',
        'CHALLENGE_VALIDATING', 'FINALIZING', 'VERSION_STORED', 'FAILED', 'CANCELLED'
    )),
    CONSTRAINT chk_deploy_certificate_order_hash CHECK (
        request_sha256 ~ '^[0-9a-f]{64}$'
        AND (external_order_digest IS NULL OR external_order_digest ~ '^[0-9a-f]{64}$')
    ),
    CONSTRAINT chk_deploy_certificate_order_attempts CHECK (attempt_count BETWEEN 0 AND 1000),
    CONSTRAINT chk_deploy_certificate_order_lease CHECK (
        (lease_owner IS NULL AND lease_expires_at IS NULL)
        OR (lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
    )
);

CREATE INDEX idx_deploy_certificate_order_due
    ON deploy_certificate_order (status, next_attempt_at, lease_expires_at, id)
    WHERE status NOT IN ('VERSION_STORED', 'FAILED', 'CANCELLED');

ALTER TABLE deploy_certificate_version
    ADD CONSTRAINT fk_deploy_certificate_version_order FOREIGN KEY (source_order_id) REFERENCES deploy_certificate_order(id);

CREATE TABLE deploy_certificate_challenge (
    id                    BIGINT       NOT NULL,
    uuid                  VARCHAR(36)  NOT NULL,
    tenant_id             BIGINT       NOT NULL,
    order_id              BIGINT       NOT NULL,
    identifier_id         BIGINT       NOT NULL,
    challenge_type        VARCHAR(16)  NOT NULL,
    proof_sha256          VARCHAR(64)  NOT NULL,
    proof_secret_ref      VARCHAR(1024),
    presentation_ref      VARCHAR(1024),
    status                VARCHAR(24)  NOT NULL DEFAULT 'PENDING',
    attempt_count         INTEGER      NOT NULL DEFAULT 0,
    next_attempt_at       TIMESTAMPTZ,
    checked_at            TIMESTAMPTZ,
    validated_at          TIMESTAMPTZ,
    last_error_code       VARCHAR(64),
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version               BIGINT       NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_certificate_challenge_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_certificate_challenge_identifier UNIQUE (order_id, identifier_id),
    CONSTRAINT fk_deploy_certificate_challenge_order FOREIGN KEY (order_id) REFERENCES deploy_certificate_order(id),
    CONSTRAINT fk_deploy_certificate_challenge_identifier FOREIGN KEY (identifier_id) REFERENCES deploy_certificate_identifier(id),
    CONSTRAINT chk_deploy_certificate_challenge_type CHECK (challenge_type IN ('HTTP_01', 'DNS_01')),
    CONSTRAINT chk_deploy_certificate_challenge_status CHECK (status IN ('PENDING', 'PRESENTING', 'PRESENTED', 'VALIDATING', 'VALID', 'FAILED', 'CLEANED')),
    CONSTRAINT chk_deploy_certificate_challenge_hash CHECK (proof_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_deploy_certificate_challenge_secret_ref CHECK (
        proof_secret_ref IS NULL OR proof_secret_ref LIKE 'secret://%'
    )
);

CREATE INDEX idx_deploy_certificate_challenge_due
    ON deploy_certificate_challenge (status, next_attempt_at, id)
    WHERE status NOT IN ('VALID', 'FAILED', 'CLEANED');

CREATE TABLE deploy_certificate_distribution (
    id                    BIGINT       NOT NULL,
    uuid                  VARCHAR(36)  NOT NULL,
    tenant_id             BIGINT       NOT NULL,
    certificate_version_id BIGINT      NOT NULL,
    node_target_id        BIGINT       NOT NULL,
    authorization_ref     VARCHAR(1024) NOT NULL,
    authorization_expires_at TIMESTAMPTZ NOT NULL,
    desired_state         VARCHAR(16)  NOT NULL DEFAULT 'PRESENT',
    status                VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version               BIGINT       NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_certificate_distribution_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_certificate_distribution_target UNIQUE (certificate_version_id, node_target_id),
    CONSTRAINT fk_deploy_certificate_distribution_version FOREIGN KEY (certificate_version_id) REFERENCES deploy_certificate_version(id),
    CONSTRAINT fk_deploy_certificate_distribution_target FOREIGN KEY (node_target_id) REFERENCES deploy_web_node_target(id),
    CONSTRAINT chk_deploy_certificate_distribution_auth_ref CHECK (authorization_ref LIKE 'secret://%'),
    CONSTRAINT chk_deploy_certificate_distribution_desired CHECK (desired_state IN ('PRESENT', 'ABSENT')),
    CONSTRAINT chk_deploy_certificate_distribution_status CHECK (status IN ('PENDING', 'AUTHORIZED', 'MATERIAL_READY', 'FAILED', 'EXPIRED', 'REVOKED'))
);

CREATE INDEX idx_deploy_certificate_distribution_expiry
    ON deploy_certificate_distribution (status, authorization_expires_at, id)
    WHERE status IN ('PENDING', 'AUTHORIZED', 'MATERIAL_READY');

CREATE TABLE deploy_tls_runtime_snapshot (
    id                    BIGINT       NOT NULL,
    uuid                  VARCHAR(36)  NOT NULL,
    tenant_id             BIGINT       NOT NULL,
    node_target_id        BIGINT       NOT NULL,
    listener_key          VARCHAR(128) NOT NULL,
    generation            BIGINT       NOT NULL,
    snapshot_sha256       VARCHAR(64)  NOT NULL,
    assignment_count      INTEGER      NOT NULL,
    status                VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    published_at          TIMESTAMPTZ,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version               BIGINT       NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_tls_runtime_snapshot_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_tls_runtime_snapshot_generation UNIQUE (node_target_id, listener_key, generation),
    CONSTRAINT fk_deploy_tls_runtime_snapshot_target FOREIGN KEY (node_target_id) REFERENCES deploy_web_node_target(id),
    CONSTRAINT chk_deploy_tls_runtime_snapshot_generation CHECK (generation BETWEEN 1 AND 9007199254740991),
    CONSTRAINT chk_deploy_tls_runtime_snapshot_hash CHECK (snapshot_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_deploy_tls_runtime_snapshot_count CHECK (assignment_count BETWEEN 0 AND 10000),
    CONSTRAINT chk_deploy_tls_runtime_snapshot_status CHECK (status IN ('PENDING', 'PUBLISHED', 'ACTIVE', 'FAILED', 'SUPERSEDED'))
);

CREATE TABLE deploy_tls_runtime_assignment (
    id                    BIGINT       NOT NULL,
    uuid                  VARCHAR(36)  NOT NULL,
    tenant_id             BIGINT       NOT NULL,
    snapshot_id           BIGINT       NOT NULL,
    listener_certificate_binding_id BIGINT NOT NULL,
    certificate_version_id BIGINT      NOT NULL,
    server_name           VARCHAR(253) NOT NULL,
    key_algorithm         VARCHAR(16)  NOT NULL,
    expected_fingerprint_sha256 VARCHAR(64) NOT NULL,
    material_ref          VARCHAR(128) NOT NULL,
    position              INTEGER      NOT NULL,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_tls_runtime_assignment_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_tls_runtime_assignment_sni UNIQUE (snapshot_id, server_name, key_algorithm),
    CONSTRAINT uk_deploy_tls_runtime_assignment_position UNIQUE (snapshot_id, position),
    CONSTRAINT fk_deploy_tls_runtime_assignment_snapshot FOREIGN KEY (snapshot_id) REFERENCES deploy_tls_runtime_snapshot(id),
    CONSTRAINT fk_deploy_tls_runtime_assignment_binding FOREIGN KEY (listener_certificate_binding_id) REFERENCES deploy_listener_certificate_binding(id),
    CONSTRAINT fk_deploy_tls_runtime_assignment_version FOREIGN KEY (certificate_version_id) REFERENCES deploy_certificate_version(id),
    CONSTRAINT chk_deploy_tls_runtime_assignment_algorithm CHECK (key_algorithm IN ('RSA', 'ECDSA')),
    CONSTRAINT chk_deploy_tls_runtime_assignment_fingerprint CHECK (expected_fingerprint_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_deploy_tls_runtime_assignment_material CHECK (material_ref ~ '^file:[0-9a-zA-Z._-]{1,120}$'),
    CONSTRAINT chk_deploy_tls_runtime_assignment_position CHECK (position BETWEEN 0 AND 9999)
);

CREATE TABLE deploy_tls_target_observation (
    id                    BIGINT       NOT NULL,
    uuid                  VARCHAR(36)  NOT NULL,
    tenant_id             BIGINT       NOT NULL,
    snapshot_id           BIGINT       NOT NULL,
    node_target_id        BIGINT       NOT NULL,
    remote_observation_uuid VARCHAR(128) NOT NULL,
    generation            BIGINT       NOT NULL,
    state                 VARCHAR(24)  NOT NULL,
    served_fingerprint_sha256 VARCHAR(64),
    probe_vantage         VARCHAR(128),
    reason_code           VARCHAR(64),
    observed_at           TIMESTAMPTZ  NOT NULL,
    ingested_at           TIMESTAMPTZ  NOT NULL,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_tls_target_observation_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_tls_target_observation_remote UNIQUE (remote_observation_uuid),
    CONSTRAINT uk_deploy_tls_target_observation_state UNIQUE (snapshot_id, state, probe_vantage),
    CONSTRAINT fk_deploy_tls_target_observation_snapshot FOREIGN KEY (snapshot_id) REFERENCES deploy_tls_runtime_snapshot(id),
    CONSTRAINT fk_deploy_tls_target_observation_target FOREIGN KEY (node_target_id) REFERENCES deploy_web_node_target(id),
    CONSTRAINT chk_deploy_tls_target_observation_generation CHECK (generation BETWEEN 1 AND 9007199254740991),
    CONSTRAINT chk_deploy_tls_target_observation_state CHECK (state IN ('RECEIVED', 'MATERIAL_READY', 'LOADED', 'SERVED', 'PUBLIC_VERIFIED', 'FAILED')),
    CONSTRAINT chk_deploy_tls_target_observation_fingerprint CHECK (
        served_fingerprint_sha256 IS NULL OR served_fingerprint_sha256 ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT chk_deploy_tls_target_observation_failure CHECK (
        (state = 'FAILED' AND reason_code IS NOT NULL)
        OR (state <> 'FAILED' AND reason_code IS NULL)
    )
);

CREATE INDEX idx_deploy_tls_target_observation_rollout
    ON deploy_tls_target_observation (tenant_id, snapshot_id, state, node_target_id, id DESC);
