-- SDKWork deploy consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_deploy_legacy_baseline.sql
-- Consolidated legacy baseline imported by bootstrap-database-module.mjs
-- Review and replace with contract-first migrations.

-- source: migrations/001_create_deploy_site.sql
-- Migration: 001_create_deploy_site
-- Description: 创建站点管理主表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_site (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    organization_id BIGINT       NOT NULL DEFAULT 0,
    data_scope      INTEGER      NOT NULL DEFAULT 1,
    user_id         BIGINT,
    name            VARCHAR(100) NOT NULL,
    slug            VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    site_type       INTEGER      NOT NULL DEFAULT 1,
    status          INTEGER      NOT NULL DEFAULT 0,
    runtime_config  JSONB        NOT NULL DEFAULT '{}',
    metadata        JSONB        NOT NULL DEFAULT '{}',
    default_variant_id BIGINT,
    current_revision_id BIGINT,
    desired_revision_id BIGINT,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    deleted_at      TIMESTAMPTZ,
    deleted_by      BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_site_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_slug UNIQUE (tenant_id, slug),
    CONSTRAINT chk_deploy_site_type CHECK (site_type BETWEEN 1 AND 6),
    CONSTRAINT chk_deploy_site_status CHECK (status BETWEEN 0 AND 3)
);

COMMENT ON TABLE deploy_site IS '站点主表';
COMMENT ON COLUMN deploy_site.id IS '雪花ID主键';
COMMENT ON COLUMN deploy_site.uuid IS '外部稳定标识';
COMMENT ON COLUMN deploy_site.tenant_id IS '租户ID';
COMMENT ON COLUMN deploy_site.organization_id IS '组织ID，0表示租户级';
COMMENT ON COLUMN deploy_site.data_scope IS '数据可见范围：1=私有，2=组织，3=租户';
COMMENT ON COLUMN deploy_site.user_id IS '创建者用户ID';
COMMENT ON COLUMN deploy_site.name IS '站点名称';
COMMENT ON COLUMN deploy_site.slug IS 'URL友好标识，租户内唯一';
COMMENT ON COLUMN deploy_site.site_type IS '站点类型：1=静态，2=SPA，3=Node，4=PHP，5=Python，6=自定义';
COMMENT ON COLUMN deploy_site.status IS '状态：0=草稿，1=活跃，2=暂停，3=归档';
COMMENT ON COLUMN deploy_site.runtime_config IS '运行时配置JSON';
COMMENT ON COLUMN deploy_site.version IS '乐观锁版本号';

CREATE INDEX idx_deploy_site_tenant_status_updated
    ON deploy_site (tenant_id, organization_id, status, updated_at DESC);

CREATE INDEX idx_deploy_site_user_updated
    ON deploy_site (tenant_id, user_id, updated_at DESC);

CREATE INDEX idx_deploy_site_slug
    ON deploy_site (tenant_id, slug);

-- source: migrations/002_create_deploy_domain.sql
-- Migration: 002_create_deploy_domain
-- Description: 创建域名绑定表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_domain (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    organization_id BIGINT       NOT NULL DEFAULT 0,
    site_id         BIGINT       NOT NULL,
    hostname        VARCHAR(255) NOT NULL,
    is_primary      BOOLEAN      NOT NULL DEFAULT false,
    is_verified     BOOLEAN      NOT NULL DEFAULT false,
    verify_token    VARCHAR(128),
    ssl_enabled     BOOLEAN      NOT NULL DEFAULT false,
    ssl_provider    VARCHAR(32),
    redirect_target VARCHAR(2000),
    status          INTEGER      NOT NULL DEFAULT 0,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    deleted_at      TIMESTAMPTZ,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_domain_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_domain_hostname UNIQUE (hostname),
    CONSTRAINT fk_deploy_domain_site FOREIGN KEY (site_id) REFERENCES deploy_site(id)
);

COMMENT ON TABLE deploy_domain IS '域名绑定表';
COMMENT ON COLUMN deploy_domain.hostname IS '域名，全局唯一';
COMMENT ON COLUMN deploy_domain.is_primary IS '是否主域名';
COMMENT ON COLUMN deploy_domain.is_verified IS '是否已验证所有权';
COMMENT ON COLUMN deploy_domain.ssl_enabled IS '是否启用SSL';
COMMENT ON COLUMN deploy_domain.ssl_provider IS '证书提供者：letsencrypt, custom, none';
COMMENT ON COLUMN deploy_domain.status IS '状态：0=待处理，1=活跃，2=错误';

CREATE INDEX idx_deploy_domain_site
    ON deploy_domain (site_id);

CREATE INDEX idx_deploy_domain_tenant_status
    ON deploy_domain (tenant_id, status);

-- source: migrations/003_create_deploy_nginx_config.sql
-- Migration: 003_create_deploy_nginx_config
-- Description: 创建 Nginx 配置版本表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_nginx_config (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    site_id         BIGINT       NOT NULL,
    domain_id       BIGINT,
    config_type     INTEGER      NOT NULL DEFAULT 1,
    config_name     VARCHAR(200) NOT NULL,
    config_content  TEXT         NOT NULL,
    config_hash     VARCHAR(64)  NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT false,
    version_no      INTEGER      NOT NULL DEFAULT 1,
    deployed_at     TIMESTAMPTZ,
    status          INTEGER      NOT NULL DEFAULT 0,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_nginx_config_uuid UNIQUE (uuid),
    CONSTRAINT fk_deploy_nginx_config_site FOREIGN KEY (site_id) REFERENCES deploy_site(id)
);

COMMENT ON TABLE deploy_nginx_config IS 'Nginx配置版本表';
COMMENT ON COLUMN deploy_nginx_config.config_type IS '配置类型：1=站点，2=上游，3=SSL，4=自定义';
COMMENT ON COLUMN deploy_nginx_config.config_content IS 'Nginx配置内容';
COMMENT ON COLUMN deploy_nginx_config.config_hash IS '配置内容SHA-256哈希';
COMMENT ON COLUMN deploy_nginx_config.is_active IS '是否为当前活跃配置';
COMMENT ON COLUMN deploy_nginx_config.version_no IS '配置版本号';
COMMENT ON COLUMN deploy_nginx_config.deployed_at IS '部署时间';
COMMENT ON COLUMN deploy_nginx_config.status IS '状态：0=草稿，1=活跃，2=归档';

CREATE INDEX idx_deploy_nginx_config_site_active
    ON deploy_nginx_config (site_id, is_active);

CREATE INDEX idx_deploy_nginx_config_type_status
    ON deploy_nginx_config (config_type, status);

-- source: migrations/004_create_deploy_certificate.sql
-- Migration: 004_create_deploy_certificate
-- Description: 创建 SSL 证书表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_certificate (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    domain_id       BIGINT,
    site_id         BIGINT,
    cert_name       VARCHAR(200) NOT NULL,
    cert_type       INTEGER      NOT NULL DEFAULT 1,
    issuer          VARCHAR(200),
    subject         VARCHAR(500),
    san_list        TEXT,
    fingerprint     VARCHAR(128),
    cert_path       VARCHAR(500),
    key_path        VARCHAR(500),
    chain_path      VARCHAR(500),
    not_before      TIMESTAMPTZ,
    not_after       TIMESTAMPTZ,
    auto_renew      BOOLEAN      NOT NULL DEFAULT true,
    renewal_status  INTEGER      NOT NULL DEFAULT 0,
    status          INTEGER      NOT NULL DEFAULT 0,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_certificate_uuid UNIQUE (uuid)
);

COMMENT ON TABLE deploy_certificate IS 'SSL证书表';
COMMENT ON COLUMN deploy_certificate.cert_type IS '证书类型：1=Let''s Encrypt，2=自定义，3=自签名';
COMMENT ON COLUMN deploy_certificate.san_list IS 'Subject Alternative Names，逗号分隔';
COMMENT ON COLUMN deploy_certificate.auto_renew IS '是否自动续期';
COMMENT ON COLUMN deploy_certificate.renewal_status IS '续期状态：0=无，1=已计划，2=处理中，3=失败';
COMMENT ON COLUMN deploy_certificate.status IS '状态：0=待处理，1=活跃，2=过期，3=已撤销';

CREATE INDEX idx_deploy_certificate_domain
    ON deploy_certificate (domain_id);

CREATE INDEX idx_deploy_certificate_expiry
    ON deploy_certificate (not_after)
    WHERE status = 1;

CREATE INDEX idx_deploy_certificate_renewal
    ON deploy_certificate (renewal_status, not_after)
    WHERE auto_renew = true AND status = 1;

-- source: migrations/005_create_deploy_deployment.sql
-- Migration: 005_create_deploy_deployment
-- Description: 创建部署记录表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_deployment (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    organization_id BIGINT       NOT NULL DEFAULT 0,
    user_id         BIGINT,
    site_id         BIGINT       NOT NULL,
    deploy_type     INTEGER      NOT NULL DEFAULT 1,
    version_tag     VARCHAR(100),
    commit_hash     VARCHAR(64),
    source_ref      VARCHAR(500),
    build_log       TEXT,
    deploy_log      TEXT,
    artifact_path   VARCHAR(500),
    artifact_size   BIGINT,
    artifact_hash   VARCHAR(64),
    environment     VARCHAR(32)  NOT NULL DEFAULT 'production',
    status          INTEGER      NOT NULL DEFAULT 0,
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    duration_ms     BIGINT,
    rollback_from   BIGINT,
    idempotency_key VARCHAR(200),
    request_id      VARCHAR(128),
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_deployment_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_deployment_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT fk_deploy_deployment_site FOREIGN KEY (site_id) REFERENCES deploy_site(id)
);

COMMENT ON TABLE deploy_deployment IS '部署记录表';
COMMENT ON COLUMN deploy_deployment.deploy_type IS '部署类型：1=上传，2=Git，3=CI/CD，4=API';
COMMENT ON COLUMN deploy_deployment.status IS '状态：0=待处理，1=构建中，2=部署中，3=成功，4=失败，5=已回滚';
COMMENT ON COLUMN deploy_deployment.duration_ms IS '部署耗时（毫秒）';
COMMENT ON COLUMN deploy_deployment.rollback_from IS '回滚来源部署ID';
COMMENT ON COLUMN deploy_deployment.idempotency_key IS '幂等键，租户内唯一';

CREATE INDEX idx_deploy_deployment_site_created
    ON deploy_deployment (site_id, created_at DESC);

CREATE INDEX idx_deploy_deployment_tenant_status
    ON deploy_deployment (tenant_id, status, created_at DESC);

CREATE INDEX idx_deploy_deployment_status
    ON deploy_deployment (status)
    WHERE status IN (0, 1, 2);

-- source: migrations/006_create_deploy_env_variable.sql
-- Migration: 006_create_deploy_env_variable
-- Description: 创建环境变量表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_env_variable (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    site_id         BIGINT       NOT NULL,
    environment     VARCHAR(32)  NOT NULL DEFAULT 'production',
    key             VARCHAR(200) NOT NULL,
    value_encrypted TEXT         NOT NULL,
    is_secret       BOOLEAN      NOT NULL DEFAULT true,
    status          INTEGER      NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_env_variable_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_env_variable_key UNIQUE (site_id, environment, key)
);

COMMENT ON TABLE deploy_env_variable IS '环境变量表';
COMMENT ON COLUMN deploy_env_variable.key IS '变量名';
COMMENT ON COLUMN deploy_env_variable.value_encrypted IS '加密存储的变量值';
COMMENT ON COLUMN deploy_env_variable.is_secret IS '是否为密钥类型';
COMMENT ON COLUMN deploy_env_variable.environment IS '所属环境';

CREATE INDEX idx_deploy_env_variable_site_env
    ON deploy_env_variable (site_id, environment);

-- source: migrations/007_create_deploy_health_check.sql
-- Migration: 007_create_deploy_health_check
-- Description: 创建健康检查配置表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_health_check (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    site_id         BIGINT       NOT NULL,
    domain_id       BIGINT,
    check_type      INTEGER      NOT NULL DEFAULT 1,
    check_url       VARCHAR(2000),
    check_interval  INTEGER      NOT NULL DEFAULT 60,
    timeout_ms      INTEGER      NOT NULL DEFAULT 5000,
    retry_count     INTEGER      NOT NULL DEFAULT 3,
    expected_status INTEGER,
    expected_body   VARCHAR(500),
    status          INTEGER      NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_health_check_uuid UNIQUE (uuid),
    CONSTRAINT fk_deploy_health_check_site FOREIGN KEY (site_id) REFERENCES deploy_site(id)
);

COMMENT ON TABLE deploy_health_check IS '健康检查配置表';
COMMENT ON COLUMN deploy_health_check.check_type IS '检查类型：1=HTTP，2=TCP，3=Ping';
COMMENT ON COLUMN deploy_health_check.check_interval IS '检查间隔（秒）';
COMMENT ON COLUMN deploy_health_check.timeout_ms IS '超时时间（毫秒）';
COMMENT ON COLUMN deploy_health_check.retry_count IS '重试次数';

CREATE INDEX idx_deploy_health_check_site
    ON deploy_health_check (site_id);

-- source: migrations/008_create_deploy_health_result.sql
-- Migration: 008_create_deploy_health_result
-- Description: 创建健康检查结果表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_health_result (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    health_check_id BIGINT       NOT NULL,
    site_id         BIGINT       NOT NULL,
    is_healthy      BOOLEAN      NOT NULL,
    response_ms     INTEGER,
    status_code     INTEGER,
    error_message   VARCHAR(1000),
    checked_at      TIMESTAMPTZ  NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE deploy_health_result IS '健康检查结果表';
COMMENT ON COLUMN deploy_health_result.is_healthy IS '是否健康';
COMMENT ON COLUMN deploy_health_result.response_ms IS '响应时间（毫秒）';
COMMENT ON COLUMN deploy_health_result.status_code IS 'HTTP状态码';
COMMENT ON COLUMN deploy_health_result.checked_at IS '检查时间';

CREATE INDEX idx_deploy_health_result_check_time
    ON deploy_health_result (health_check_id, checked_at DESC);

CREATE INDEX idx_deploy_health_result_site_time
    ON deploy_health_result (site_id, checked_at DESC);

-- source: migrations/009_create_deploy_audit_log.sql
-- Migration: 009_create_deploy_audit_log
-- Description: 创建操作审计日志表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-14

CREATE TABLE deploy_audit_log (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    organization_id BIGINT       NOT NULL DEFAULT 0,
    operator_id     BIGINT       NOT NULL,
    operator_type   VARCHAR(32)  NOT NULL DEFAULT 'USER',
    action          VARCHAR(100) NOT NULL,
    target_type     VARCHAR(100) NOT NULL,
    target_id       BIGINT,
    target_uuid     VARCHAR(64),
    request_id      VARCHAR(128),
    ip_address      VARCHAR(45),
    user_agent      VARCHAR(500),
    changes         JSONB,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE deploy_audit_log IS '操作审计日志表';
COMMENT ON COLUMN deploy_audit_log.operator_id IS '操作人ID';
COMMENT ON COLUMN deploy_audit_log.operator_type IS '操作人类型：USER, SYSTEM, ADMIN, JOB, SERVICE';
COMMENT ON COLUMN deploy_audit_log.action IS '操作类型';
COMMENT ON COLUMN deploy_audit_log.target_type IS '目标对象类型';
COMMENT ON COLUMN deploy_audit_log.target_id IS '目标对象ID';
COMMENT ON COLUMN deploy_audit_log.changes IS '变更内容JSON：{"field": {"old": x, "new": y}}';

CREATE INDEX idx_deploy_audit_log_target
    ON deploy_audit_log (target_type, target_id, created_at DESC);

CREATE INDEX idx_deploy_audit_log_operator
    ON deploy_audit_log (operator_id, created_at DESC);

CREATE INDEX idx_deploy_audit_log_tenant_action
    ON deploy_audit_log (tenant_id, action, created_at DESC);

-- source: migrations/010_create_deploy_server.sql
-- Migration: 010_create_deploy_server
-- Description: 创建后端部署服务器表
-- Author: SDKWork Deploy Server
-- Date: 2026-06-23

CREATE TABLE deploy_server (
    id              BIGINT       NOT NULL,
    uuid            VARCHAR(64)  NOT NULL,
    tenant_id       BIGINT       NOT NULL DEFAULT 0,
    name            VARCHAR(200) NOT NULL,
    host            VARCHAR(255) NOT NULL,
    ssh_port        INTEGER      NOT NULL DEFAULT 22,
    status          INTEGER      NOT NULL DEFAULT 0,
    metadata        JSONB        NOT NULL DEFAULT '{}',
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,
    version         BIGINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_deploy_server_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_server_host UNIQUE (tenant_id, host)
);

COMMENT ON TABLE deploy_server IS '部署后端服务器表';
COMMENT ON COLUMN deploy_server.status IS '状态：0=未连接，1=在线，2=离线，3=维护中';

CREATE INDEX idx_deploy_server_tenant_status
    ON deploy_server (tenant_id, status, updated_at DESC);

-- folded migration: migrations/postgres/0001_deploy_upload_session_ref.up.sql
-- deploy upload session references (Drive-backed artifact lifecycle)
CREATE TABLE IF NOT EXISTS deploy_upload_session_ref (
    id BIGINT PRIMARY KEY NOT NULL,
    uuid VARCHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    site_id BIGINT NULL,
    drive_upload_session_id VARCHAR(128) NOT NULL,
    drive_upload_item_id VARCHAR(128) NULL,
    drive_space_id VARCHAR(128) NULL,
    drive_node_id VARCHAR(128) NULL,
    package_type INTEGER NOT NULL,
    file_name VARCHAR(500) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    content_length BIGINT NOT NULL,
    checksum VARCHAR(128) NULL,
    status INTEGER NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_upload_session_ref_uuid
    ON deploy_upload_session_ref (uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_upload_session_ref_idempotency
    ON deploy_upload_session_ref (tenant_id, idempotency_key)
    WHERE deleted_at IS NULL;

-- folded migration: migrations/postgres/0002_deploy_certificate_idempotency_key.up.sql
ALTER TABLE deploy_certificate
    ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(128);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_certificate_idempotency
    ON deploy_certificate (tenant_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

-- folded migration: migrations/postgres/0003_deploy_artifact_release.up.sql
-- Immutable artifacts from completed package upload sessions
CREATE TABLE IF NOT EXISTS deploy_artifact (
    id BIGINT PRIMARY KEY NOT NULL,
    uuid VARCHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    site_id BIGINT NULL,
    upload_session_ref_id BIGINT NOT NULL,
    package_type INTEGER NOT NULL,
    file_name VARCHAR(500) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    content_length BIGINT NOT NULL,
    checksum_sha256 VARCHAR(128) NULL,
    drive_node_id VARCHAR(128) NOT NULL,
    drive_space_id VARCHAR(128) NULL,
    drive_path VARCHAR(500) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_deploy_artifact_upload_session
        FOREIGN KEY (upload_session_ref_id) REFERENCES deploy_upload_session_ref(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_artifact_uuid
    ON deploy_artifact (uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_artifact_upload_session
    ON deploy_artifact (upload_session_ref_id);

CREATE INDEX IF NOT EXISTS idx_deploy_artifact_tenant_created
    ON deploy_artifact (tenant_id, created_at DESC);

-- Immutable site releases referencing one artifact
CREATE TABLE IF NOT EXISTS deploy_release (
    id BIGINT PRIMARY KEY NOT NULL,
    uuid VARCHAR(36) NOT NULL,
    tenant_id BIGINT NOT NULL,
    site_id BIGINT NOT NULL,
    artifact_id BIGINT NOT NULL,
    version_tag VARCHAR(100) NULL,
    status INTEGER NOT NULL DEFAULT 1,
    idempotency_key VARCHAR(128) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_deploy_release_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT fk_deploy_release_artifact FOREIGN KEY (artifact_id) REFERENCES deploy_artifact(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_release_uuid
    ON deploy_release (uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_deploy_release_idempotency
    ON deploy_release (tenant_id, site_id, idempotency_key);

CREATE INDEX IF NOT EXISTS idx_deploy_release_site_created
    ON deploy_release (site_id, created_at DESC);

ALTER TABLE deploy_deployment
    ADD COLUMN IF NOT EXISTS release_id BIGINT NULL;

CREATE INDEX IF NOT EXISTS idx_deploy_deployment_release
    ON deploy_deployment (release_id)
    WHERE release_id IS NOT NULL;

-- Live website composition. Provider UUIDs are opaque owner-service identities; source content
-- versions, object keys, URLs, and credentials never enter these configuration tables.
CREATE TABLE deploy_site_resource (
    id                        BIGINT PRIMARY KEY NOT NULL,
    uuid                      VARCHAR(36) NOT NULL,
    tenant_id                 BIGINT NOT NULL,
    organization_id           BIGINT NOT NULL DEFAULT 0,
    site_id                   BIGINT NOT NULL,
    resource_key              VARCHAR(64) NOT NULL,
    provider_type             VARCHAR(32) NOT NULL,
    provider_resource_uuid    VARCHAR(128) NOT NULL,
    provider_contract_version VARCHAR(64) NOT NULL,
    capabilities_json         JSONB NOT NULL DEFAULT '{}',
    status                    VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    last_validated_at         TIMESTAMPTZ NULL,
    last_error_code           VARCHAR(64) NULL,
    metadata                  JSONB NOT NULL DEFAULT '{}',
    created_by                BIGINT NULL,
    updated_by                BIGINT NULL,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version                   BIGINT NOT NULL DEFAULT 1,
    deleted_at                TIMESTAMPTZ NULL,
    CONSTRAINT uk_deploy_site_resource_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_resource_key UNIQUE (site_id, resource_key),
    CONSTRAINT fk_deploy_site_resource_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT chk_deploy_site_resource_provider CHECK (provider_type IN ('DRIVE', 'KNOWLEDGEBASE')),
    CONSTRAINT chk_deploy_site_resource_status CHECK (status IN ('PENDING', 'VALID', 'INVALID', 'UNAVAILABLE', 'REVOKED'))
);

CREATE INDEX idx_deploy_site_resource_site_status
    ON deploy_site_resource (tenant_id, site_id, status)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_deploy_site_resource_provider
    ON deploy_site_resource (tenant_id, provider_type, provider_resource_uuid)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_site_variant (
    id              BIGINT PRIMARY KEY NOT NULL,
    uuid            VARCHAR(36) NOT NULL,
    tenant_id       BIGINT NOT NULL,
    site_id         BIGINT NOT NULL,
    variant_key     VARCHAR(64) NOT NULL,
    label           VARCHAR(64) NOT NULL,
    client_class    VARCHAR(16) NOT NULL DEFAULT 'OTHER',
    is_default      BOOLEAN NOT NULL DEFAULT FALSE,
    priority        INTEGER NOT NULL DEFAULT 0,
    status          VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    metadata        JSONB NOT NULL DEFAULT '{}',
    created_by      BIGINT NULL,
    updated_by      BIGINT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version         BIGINT NOT NULL DEFAULT 1,
    deleted_at      TIMESTAMPTZ NULL,
    CONSTRAINT uk_deploy_site_variant_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_variant_key UNIQUE (site_id, variant_key),
    CONSTRAINT fk_deploy_site_variant_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT chk_deploy_site_variant_client CHECK (client_class IN ('DESKTOP', 'MOBILE', 'TABLET', 'BOT', 'OTHER')),
    CONSTRAINT chk_deploy_site_variant_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE UNIQUE INDEX uk_deploy_site_variant_default
    ON deploy_site_variant (site_id)
    WHERE is_default = TRUE AND status = 'ACTIVE' AND deleted_at IS NULL;

CREATE INDEX idx_deploy_site_variant_site_priority
    ON deploy_site_variant (tenant_id, site_id, status, priority, uuid)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_site_variant_rule (
    id                BIGINT PRIMARY KEY NOT NULL,
    uuid              VARCHAR(36) NOT NULL,
    tenant_id         BIGINT NOT NULL,
    site_id           BIGINT NOT NULL,
    rule_key          VARCHAR(64) NOT NULL,
    target_variant_id BIGINT NOT NULL,
    rule_type         VARCHAR(16) NOT NULL,
    match_value       VARCHAR(4096) NOT NULL,
    priority          INTEGER NOT NULL DEFAULT 0,
    status            VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_by        BIGINT NULL,
    updated_by        BIGINT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version           BIGINT NOT NULL DEFAULT 1,
    deleted_at        TIMESTAMPTZ NULL,
    CONSTRAINT uk_deploy_site_variant_rule_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_variant_rule_key UNIQUE (site_id, rule_key),
    CONSTRAINT fk_deploy_site_variant_rule_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT fk_deploy_site_variant_rule_variant FOREIGN KEY (target_variant_id) REFERENCES deploy_site_variant(id),
    CONSTRAINT chk_deploy_site_variant_rule_type CHECK (rule_type IN ('PATH_PREFIX', 'CLIENT_CLASS')),
    CONSTRAINT chk_deploy_site_variant_rule_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT chk_deploy_site_variant_rule_priority CHECK (priority BETWEEN 0 AND 65535)
);

CREATE INDEX idx_deploy_site_variant_rule_order
    ON deploy_site_variant_rule (tenant_id, site_id, status, priority, uuid)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_site_mount (
    id                BIGINT PRIMARY KEY NOT NULL,
    uuid              VARCHAR(36) NOT NULL,
    tenant_id         BIGINT NOT NULL,
    site_id           BIGINT NOT NULL,
    mount_key         VARCHAR(64) NOT NULL,
    variant_id        BIGINT NOT NULL,
    resource_id       BIGINT NOT NULL,
    path_prefix       VARCHAR(4096) NOT NULL,
    resource_subpath  VARCHAR(4096) NOT NULL DEFAULT '/',
    mount_mode        VARCHAR(16) NOT NULL DEFAULT 'ROOT',
    handler_type      VARCHAR(16) NOT NULL,
    index_files_json  JSONB NOT NULL DEFAULT '[]',
    spa_fallback_path VARCHAR(4096) NULL,
    priority          INTEGER NOT NULL DEFAULT 0,
    status            VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_by        BIGINT NULL,
    updated_by        BIGINT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version           BIGINT NOT NULL DEFAULT 1,
    deleted_at        TIMESTAMPTZ NULL,
    CONSTRAINT uk_deploy_site_mount_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_mount_key UNIQUE (site_id, mount_key),
    CONSTRAINT uk_deploy_site_mount_prefix UNIQUE (variant_id, path_prefix),
    CONSTRAINT fk_deploy_site_mount_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT fk_deploy_site_mount_variant FOREIGN KEY (variant_id) REFERENCES deploy_site_variant(id),
    CONSTRAINT fk_deploy_site_mount_resource FOREIGN KEY (resource_id) REFERENCES deploy_site_resource(id),
    CONSTRAINT chk_deploy_site_mount_mode CHECK (mount_mode IN ('ROOT', 'ALIAS')),
    CONSTRAINT chk_deploy_site_mount_handler CHECK (handler_type IN ('STATIC', 'SPA', 'WIKI')),
    CONSTRAINT chk_deploy_site_mount_status CHECK (status IN ('ACTIVE', 'DISABLED', 'INVALID'))
);

CREATE INDEX idx_deploy_site_mount_route
    ON deploy_site_mount (tenant_id, site_id, variant_id, status, path_prefix)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_site_binding (
    id                   BIGINT PRIMARY KEY NOT NULL,
    uuid                 VARCHAR(36) NOT NULL,
    tenant_id            BIGINT NOT NULL,
    organization_id      BIGINT NOT NULL DEFAULT 0,
    site_id              BIGINT NOT NULL,
    binding_key           VARCHAR(64) NOT NULL,
    domain_id            BIGINT NOT NULL,
    hostname_ascii       VARCHAR(255) NOT NULL,
    environment          VARCHAR(16) NOT NULL,
    path_prefix          VARCHAR(4096) NOT NULL DEFAULT '/',
    action_type          VARCHAR(16) NOT NULL DEFAULT 'SERVE',
    default_variant_id   BIGINT NULL,
    forced_variant_id    BIGINT NULL,
    redirect_scheme      VARCHAR(8) NULL,
    redirect_hostname    VARCHAR(255) NULL,
    redirect_path_prefix VARCHAR(4096) NULL,
    redirect_status_code INTEGER NULL,
    preserve_path        BOOLEAN NOT NULL DEFAULT TRUE,
    preserve_query       BOOLEAN NOT NULL DEFAULT TRUE,
    status               VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    verified_at          TIMESTAMPTZ NULL,
    activated_at         TIMESTAMPTZ NULL,
    created_by           BIGINT NULL,
    updated_by           BIGINT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version              BIGINT NOT NULL DEFAULT 1,
    deleted_at           TIMESTAMPTZ NULL,
    CONSTRAINT uk_deploy_site_binding_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_binding_key UNIQUE (site_id, binding_key),
    CONSTRAINT uk_deploy_site_binding_route UNIQUE (hostname_ascii, path_prefix, environment),
    CONSTRAINT fk_deploy_site_binding_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT fk_deploy_site_binding_domain FOREIGN KEY (domain_id) REFERENCES deploy_domain(id),
    CONSTRAINT fk_deploy_site_binding_default_variant FOREIGN KEY (default_variant_id) REFERENCES deploy_site_variant(id),
    CONSTRAINT fk_deploy_site_binding_forced_variant FOREIGN KEY (forced_variant_id) REFERENCES deploy_site_variant(id),
    CONSTRAINT chk_deploy_site_binding_environment CHECK (environment IN ('development', 'test', 'staging', 'production')),
    CONSTRAINT chk_deploy_site_binding_action CHECK (action_type IN ('SERVE', 'REDIRECT')),
    CONSTRAINT chk_deploy_site_binding_status CHECK (status IN ('PENDING', 'VERIFIED', 'ACTIVE', 'PAUSED', 'FAILED', 'ARCHIVED')),
    CONSTRAINT chk_deploy_site_binding_redirect_status CHECK (redirect_status_code IS NULL OR redirect_status_code IN (301, 302, 307, 308))
);

CREATE INDEX idx_deploy_site_binding_site_status
    ON deploy_site_binding (tenant_id, site_id, environment, status)
    WHERE deleted_at IS NULL;

CREATE TABLE deploy_site_revision (
    id                        BIGINT PRIMARY KEY NOT NULL,
    uuid                      VARCHAR(36) NOT NULL,
    tenant_id                 BIGINT NOT NULL,
    organization_id           BIGINT NOT NULL DEFAULT 0,
    site_id                   BIGINT NOT NULL,
    revision_no               BIGINT NOT NULL,
    environment               VARCHAR(16) NOT NULL,
    descriptor_schema_version VARCHAR(64) NOT NULL,
    descriptor_json           JSONB NOT NULL,
    descriptor_sha256         VARCHAR(64) NOT NULL,
    compiler_version          VARCHAR(128) NOT NULL,
    source_config_version     BIGINT NOT NULL,
    idempotency_key           VARCHAR(128) NOT NULL,
    request_sha256            VARCHAR(64) NOT NULL,
    result_json               JSONB NOT NULL DEFAULT '{}',
    validation_status         VARCHAR(16) NOT NULL DEFAULT 'VALID',
    validation_report_json    JSONB NOT NULL DEFAULT '{}',
    supersedes_revision_id    BIGINT NULL,
    created_by                BIGINT NULL,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_deploy_site_revision_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_site_revision_no UNIQUE (site_id, revision_no),
    CONSTRAINT uk_deploy_site_revision_hash UNIQUE (site_id, descriptor_sha256),
    CONSTRAINT uk_deploy_site_revision_idempotency UNIQUE (tenant_id, site_id, idempotency_key),
    CONSTRAINT fk_deploy_site_revision_site FOREIGN KEY (site_id) REFERENCES deploy_site(id),
    CONSTRAINT fk_deploy_site_revision_supersedes FOREIGN KEY (supersedes_revision_id) REFERENCES deploy_site_revision(id),
    CONSTRAINT chk_deploy_site_revision_environment CHECK (environment IN ('development', 'test', 'staging', 'production')),
    CONSTRAINT chk_deploy_site_revision_validation CHECK (validation_status IN ('VALID', 'INVALID'))
);

CREATE INDEX idx_deploy_site_revision_site_created
    ON deploy_site_revision (tenant_id, site_id, revision_no DESC);

CREATE TABLE deploy_web_node_target (
    id                BIGINT PRIMARY KEY NOT NULL,
    uuid              VARCHAR(36) NOT NULL,
    tenant_id         BIGINT NOT NULL,
    node_uuid         VARCHAR(128) NOT NULL,
    environment       VARCHAR(16) NOT NULL,
    tenant_scope_hash VARCHAR(64) NOT NULL,
    region            VARCHAR(64) NULL,
    status            VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version           BIGINT NOT NULL DEFAULT 1,
    deleted_at        TIMESTAMPTZ NULL,
    CONSTRAINT uk_deploy_web_node_target_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_web_node_target_node UNIQUE (node_uuid, environment),
    CONSTRAINT chk_deploy_web_node_target_environment CHECK (environment IN ('development', 'test', 'staging', 'production')),
    CONSTRAINT chk_deploy_web_node_target_status CHECK (status IN ('ACTIVE', 'DRAINING', 'DISABLED'))
);

CREATE INDEX idx_deploy_web_node_target_tenant
    ON deploy_web_node_target (tenant_id, environment, status, node_uuid)
    WHERE deleted_at IS NULL;

-- Durable desired-state/outbox row. Web Server owns the delivery projection and Node observation;
-- Deployments retains the exact bytes and publication result needed for idempotent reconciliation.
CREATE TABLE deploy_runtime_assignment (
    id                     BIGINT PRIMARY KEY NOT NULL,
    uuid                   VARCHAR(36) NOT NULL,
    tenant_id              BIGINT NOT NULL,
    node_target_id         BIGINT NOT NULL,
    trigger_site_revision_id BIGINT NULL,
    generation             BIGINT NOT NULL,
    snapshot_uuid          VARCHAR(128) NOT NULL,
    snapshot_sha256        VARCHAR(64) NOT NULL,
    desired_state_sha256   VARCHAR(64) NOT NULL,
    runtime_set_json       JSONB NOT NULL,
    runtime_set_bytes      BIGINT NOT NULL,
    publish_status         VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    remote_assignment_uuid VARCHAR(128) NULL,
    attempt_count          INTEGER NOT NULL DEFAULT 0,
    next_attempt_at        TIMESTAMPTZ NULL,
    lease_owner            VARCHAR(128) NULL,
    lease_expires_at       TIMESTAMPTZ NULL,
    last_error_code        VARCHAR(64) NULL,
    published_at           TIMESTAMPTZ NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version                BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT uk_deploy_runtime_assignment_uuid UNIQUE (uuid),
    CONSTRAINT uk_deploy_runtime_assignment_generation UNIQUE (node_target_id, generation),
    CONSTRAINT uk_deploy_runtime_assignment_snapshot UNIQUE (snapshot_uuid),
    CONSTRAINT fk_deploy_runtime_assignment_target FOREIGN KEY (node_target_id) REFERENCES deploy_web_node_target(id),
    CONSTRAINT fk_deploy_runtime_assignment_revision FOREIGN KEY (trigger_site_revision_id) REFERENCES deploy_site_revision(id),
    CONSTRAINT chk_deploy_runtime_assignment_generation CHECK (generation BETWEEN 1 AND 9007199254740991),
    CONSTRAINT chk_deploy_runtime_assignment_bytes CHECK (runtime_set_bytes > 0 AND runtime_set_bytes <= 67108864),
    CONSTRAINT chk_deploy_runtime_assignment_status CHECK (publish_status IN ('PENDING', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'SUPERSEDED')),
    CONSTRAINT chk_deploy_runtime_assignment_lease CHECK (
        (publish_status = 'PUBLISHING' AND lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)
        OR (publish_status <> 'PUBLISHING' AND lease_owner IS NULL AND lease_expires_at IS NULL)
    )
);

CREATE INDEX idx_deploy_runtime_assignment_delivery
    ON deploy_runtime_assignment (publish_status, next_attempt_at, lease_expires_at, created_at)
    WHERE publish_status IN ('PENDING', 'PUBLISHING', 'FAILED');

CREATE INDEX idx_deploy_runtime_assignment_target_latest
    ON deploy_runtime_assignment (tenant_id, node_target_id, generation DESC);
